# <center>Exploratory Data Analysis

### What is EDA?

EDA means:

Understanding a dataset before modeling.

**The EDA Workflow**

A professional analyst often follows:

1. Overview
2. Descriptive Statistics
3. Categorical Analysis
4. Numerical Analysis
5. Correlation Analysis
6. Outlier Detection
7. Business Insights

This workflow should become automatic.

Our Dataset to work on:

In [15]:
import pandas as pd
df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age":[22,25,30,28,35],
    "Salary":[50000,70000,90000,80000,120000],
    "Department":["HR","IT","IT","Finance","HR"],
})
df

     Name  Age  Salary Department
0     Ali   22   50000         HR
1    Sara   25   70000         IT
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR

**1. Describe**

In [6]:
df.describe()

             Age         Salary
count   5.000000       5.000000
mean   28.000000   82000.000000
std     4.949747   25884.358211
min    22.000000   50000.000000
25%    25.000000   70000.000000
50%    28.000000   80000.000000
75%    30.000000   90000.000000
max    35.000000  120000.000000

**Understanding Every Row**\
count : Number of non-missing values\
mean : Average\
std : Standard Deviation(Measures spread)\
min : Smallest value.\
25% : First Quartile (Q1)\
50% : Median (Q2)\
75% : Third Quartile (Q3)\
max : Largest value

**Stage 2: Categorical Analysis**

**describe(include="all")**\
Includes catergorical columns

In [7]:
df.describe(include="all")

       Name        Age         Salary Department
count     5   5.000000       5.000000          5
unique    5        NaN            NaN          3
top     Ali        NaN            NaN         HR
freq      1        NaN            NaN          2
mean    NaN  28.000000   82000.000000        NaN
std     NaN   4.949747   25884.358211        NaN
min     NaN  22.000000   50000.000000        NaN
25%     NaN  25.000000   70000.000000        NaN
50%     NaN  28.000000   80000.000000        NaN
75%     NaN  30.000000   90000.000000        NaN
max     NaN  35.000000  120000.000000        NaN

**2. Mean**

In [19]:
df["Salary"].mean()

np.float64(82000.0)

In [8]:
df.mean(numeric_only=True)

Age          28.0
Salary    82000.0
dtype: float64

**3. Median**

In [20]:
df["Age"].median()

28.0

In [11]:
df.median(numeric_only=True)

Age          28.0
Salary    80000.0
dtype: float64

**4. Mode**

In [21]:
df["Department"].mode()

0    HR
1    IT
Name: Department, dtype: object

Mode returns a Series because there may be multiple modes.

**5. Standard Deviation**

In [22]:
df["Salary"].std()

25884.35821108957

In [18]:
df.std(numeric_only=True)

Age           4.949747
Salary    25884.358211
dtype: float64

**Interpretation:**\
Large : Huge salary differences.\
Small : Employees earn similar amounts.

**6. Variance**

In [23]:
df["Salary"].var()

670000000.0

Variance = Std²

**7. Unique Values**

In [24]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [26]:
df["Department"].nunique()

3

Very common in EDA

**8. Value Counts**\
One of the most powerful pandas functions

In [29]:
df["Department"].value_counts()

Department
HR         2
IT         2
Finance    1
Name: count, dtype: int64

Normalize:

In [30]:
df["Department"].value_counts(normalize=True)

Department
HR         0.4
IT         0.4
Finance    0.2
Name: proportion, dtype: float64

**9. Quartiles**

In [36]:
df["Salary"].quantile(0.25)

np.float64(70000.0)

In [32]:
df["Salary"].quantile(0.5)

np.float64(80000.0)

In [33]:
df["Salary"].quantile(0.75)

np.float64(90000.0)

Multiple Quantiles:

In [37]:
df["Salary"].quantile([0.25,0.5,0.75,1])

0.25     70000.0
0.50     80000.0
0.75     90000.0
1.00    120000.0
Name: Salary, dtype: float64

**10. Correlation Analysis**

In [38]:
df[["Age","Salary"]].corr()

             Age    Salary
Age     1.000000  0.995153
Salary  0.995153  1.000000

**Understanding Correlation Matrix**\
**Diagonal**\
Always : 1\
Because:\
Age vs Age\
Salary vs Salary\
Perfect correlation.\
Ignore diagonals.

**Positive Correlation:**\
+1 : Perfect positive relationship.\
**Negative Correlation:**\
-1 : Perfect negative relationship.\
**No linear relationship**\
0 : Zero Correlation

**Industry Interpretation:**\
0.8–1.0 : Strong Positive\
0.5–0.8 : Moderate Positive\
0–0.5 : Weak Positive

Negative values:

Same idea.

**12. Outlier Detection**

In [39]:
q1 = df["Salary"].quantile(0.25)
q3 = df["Salary"].quantile(0.75)
iqr = q3 - q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 *iqr
outliers = df[
    (df["Salary"]<lower) | (df["Salary"]>upper)
    ]

**Professional EDA Checklist**

Whenever you get a dataset:

df.info()

df.describe()

df.isna().sum()

df.nunique()

df.corr()

df.value_counts()

These become muscle memory.