# <center> Indexing and Slicing Mastery

In Pandas, we still do selection like NumPy, but now we have:\
Labels\
Column Names\
Indexes\
Positions\
Conditions\
This makes Pandas much more expressive.

**The Big Idea**\
A DataFrame has:\
Rows\
Columns\
You must learn to access both.\
**Think:**\
Which rows?\
Which columns?\
Every selection problem is some combination of those two questions.

Let's create our dataset to work with:

In [9]:
import pandas as pd
df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age":[22,25,30,28,35],
    "Salary":[50000,70000,90000,80000,120000],
    "Department":["HR","IT","IT","Finance","HR"]
})
df.index=[101,102,103,104,105]
print(df)

       Name  Age  Salary Department
101     Ali   22   50000         HR
102    Sara   25   70000         IT
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance
105   Bilal   35  120000         HR

**1. Selecting Columns**\
Columns are selected using names.\
**Single Column**

In [10]:
df["Salary"]

101     50000
102     70000
103     90000
104     80000
105    120000
Name: Salary, dtype: int64

**Multiple Columns**

In [11]:
df[["Name","Salary"]]

       Name  Salary
101     Ali   50000
102    Sara   70000
103   Ahmed   90000
104  Ayesha   80000
105   Bilal  120000

**2. Row Selection**\
Now we select rows.\
Pandas gives us:\
.loc[]\
.iloc[]\
These are extremely important.

**loc[]**\
Think: LABEL BASED

In [13]:
df.loc[102]

Name           Sara
Age              25
Salary        70000
Department       IT
Name: 102, dtype: object

Multiple rows:

In [14]:
df.loc[[101,104]]

       Name  Age  Salary Department
101     Ali   22   50000         HR
104  Ayesha   28   80000    Finance

Range:

In [15]:
df.loc[101:103]

      Name  Age  Salary Department
101    Ali   22   50000         HR
102   Sara   25   70000         IT
103  Ahmed   30   90000         IT

Notice: Upper limit is also inclusive when working with loc[], unlike NumPy Slicing.

**iloc[]**\
Think: INTEGER POSITION BASED

In [16]:
df.iloc[1]

Name           Sara
Age              25
Salary        70000
Department       IT
Name: 102, dtype: object

Multiple rows:

In [17]:
df.iloc[[1,4]]

      Name  Age  Salary Department
102   Sara   25   70000         IT
105  Bilal   35  120000         HR

Range:

In [19]:
df.iloc[2:4]

       Name  Age  Salary Department
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance

Notice: iloc[] doesn't include upper limit, works exactly like NumPy slicing and unlike loc[].

**Selecting Rows and Columns Together**\
**1. loc**\
Syntax: df.loc[row_selection, column_selection]

In [24]:
df.loc[103,"Department"]

'IT'

In [25]:
df.loc[102:105,["Age","Salary"]]

     Age  Salary
102   25   70000
103   30   90000
104   28   80000
105   35  120000

**2. iloc**\
Syntax: df.iloc[row_selection,column_selection]

In [27]:
df.iloc[3,1]

np.int64(28)

In [29]:
df.iloc[1:4,[0,2,3]]

       Name  Salary Department
102    Sara   70000         IT
103   Ahmed   90000         IT
104  Ayesha   80000    Finance

**3. Fast Scalar Access**\
When accessing one value.\
**a. at[]**\
Label based.

In [31]:
df.at[102,"Department"]

'IT'

**b. iat[]**\
Position based.

In [34]:
df.iat[1,0]

'Sara'

These are faster than:\
df.loc[]\
df.iloc[]\
for single values.

**4. Boolean Filtering**\
This is where Pandas becomes powerful.\
**Question:**\
Show employees with salary > 70000

In [36]:
df[df["Salary"]>70000]

       Name  Age  Salary Department
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance
105   Bilal   35  120000         HR

**Multiple Conditions:**

AND:

In [37]:
df[
    (df["Salary"]>70000)
    &
    (df["Department"]=="IT")
    ]

      Name  Age  Salary Department
103  Ahmed   30   90000         IT

OR:

In [38]:
df[
    (df["Salary"]>70000)
    |
    (df["Department"]=="IT")
    ]

       Name  Age  Salary Department
102    Sara   25   70000         IT
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance
105   Bilal   35  120000         HR

NOT:

In [40]:
df[~(df["Department"]=="IT")]

       Name  Age  Salary Department
101     Ali   22   50000         HR
104  Ayesha   28   80000    Finance
105   Bilal   35  120000         HR

**5. Query Method**\
Same filtering.\
More SQL-like.

In [41]:
df.query("Salary>65000")

       Name  Age  Salary Department
102    Sara   25   70000         IT
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance
105   Bilal   35  120000         HR

In [44]:
df.query("Salary>70000 and Department=='IT'")

      Name  Age  Salary Department
103  Ahmed   30   90000         IT

**6. Sorting:**

Ascending:

In [47]:
df.sort_values("Salary")

       Name  Age  Salary Department
101     Ali   22   50000         HR
102    Sara   25   70000         IT
104  Ayesha   28   80000    Finance
103   Ahmed   30   90000         IT
105   Bilal   35  120000         HR

Descending:

In [48]:
df.sort_values("Salary",ascending=False)

       Name  Age  Salary Department
105   Bilal   35  120000         HR
103   Ahmed   30   90000         IT
104  Ayesha   28   80000    Finance
102    Sara   25   70000         IT
101     Ali   22   50000         HR

Multiple columns:

In [52]:
df.sort_values(["Salary","Age"])

       Name  Age  Salary Department
101     Ali   22   50000         HR
102    Sara   25   70000         IT
104  Ayesha   28   80000    Finance
103   Ahmed   30   90000         IT
105   Bilal   35  120000         HR

**7. Membership Testing**\
Very common.

In [53]:
df[df["Department"].isin(["HR","IT"])]

      Name  Age  Salary Department
101    Ali   22   50000         HR
102   Sara   25   70000         IT
103  Ahmed   30   90000         IT
105  Bilal   35  120000         HR

**8. Unique Values**\
Often used before analysis.

In [55]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [56]:
df["Department"].nunique()

3

## <center> Practice Problems

**Problems (1–3)**\
**1. Create an employee DataFrame with Name, Age, Salary.**\
**Retrieve:**\
Salary column\
Age column\
**2. Retrieve:**\
Name and Salary columns together\
**3. Print:**\
df.iloc[0]\
df.iloc[2]

In [73]:
emp = pd.DataFrame({
    "Name":["Ali","Zeeshan","Mustafa"],
    "Age":[20,22,23],
    "Salary":[50000,85000,65000]
})
emp[["Salary","Age"]]

   Salary  Age
0   50000   20
1   85000   22
2   65000   23

In [59]:
emp[["Name","Salary"]]

      Name  Salary
0      Ali   50000
1  Zeeshan   85000
2  Mustafa   65000

In [63]:
emp.iloc[0]

Name        Ali
Age          20
Salary    50000
Name: 0, dtype: object

In [64]:
emp.iloc[2]

Name      Mustafa
Age            23
Salary      65000
Name: 2, dtype: object

**Problems (4–6)**\
4.	Retrieve first 3 rows using:\
iloc\
5.	Retrieve rows 1–4 and columns Name and Salary using:\
loc\
6.	Find employees:\
Salary > 60000

In [65]:
emp.iloc[0:3]

      Name  Age  Salary
0      Ali   20   50000
1  Zeeshan   22   85000
2  Mustafa   23   65000

In [66]:
emp.loc[0:3,["Name","Salary"]]

      Name  Salary
0      Ali   50000
1  Zeeshan   85000
2  Mustafa   65000

In [67]:
emp[emp["Salary"]>60000]

      Name  Age  Salary
1  Zeeshan   22   85000
2  Mustafa   23   65000

**Problems (7–8)**\
7.	Find employees:\
Salary > 60000\
AND\
Age > 22\
8. Generate a DataFrame of 100 customers using NumPy.\
**Perform:**\
Salary > average salary\
Age < 25\
Top 2 highest salaries

In [71]:
emp[
    (emp["Salary"]>60000)
    &
    (emp["Age"]>22)
    ]

      Name  Age  Salary
2  Mustafa   23   65000

In [77]:
import numpy as np
Age = np.random.randint(15,28,5)
Salary = np.random.randint(40000,120000,5)
data = np.column_stack((Age,Salary))

In [78]:
data

array([[   22, 92824],
       [   27, 70265],
       [   19, 67490],
       [   16, 45041],
       [   23, 87603]], dtype=int32)

In [80]:
df = pd.DataFrame(
    data,
    columns = ["Age","Salary"]
)
df

   Age  Salary
0   22   92824
1   27   70265
2   19   67490
3   16   45041
4   23   87603

In [81]:
df[df["Salary"]>np.mean(Salary)]

   Age  Salary
0   22   92824
4   23   87603

In [82]:
df[df["Age"]<25]

   Age  Salary
0   22   92824
2   19   67490
3   16   45041
4   23   87603

In [89]:
sorted = df.sort_values("Salary",ascending=False)

In [90]:
sorted.iloc[[0,1]]

   Age  Salary
0   22   92824
4   23   87603