# <center>Transformations & Feature Engineering

Creating new data.\
Transforming existing data.\
Converting business rules into features.\
Preparing data for machine learning.

What is Feature Engineering?

Suppose we have:

Name	Age	Salary\
Ali	    22	50000\
Sara	35	120000

A business analyst might ask:

Create customer categories:

Salary < 60K  → Bronze\
60K-100K      → Silver\
100K+         → Gold

These categories don't exist.

We create them.

That's feature engineering.

**Dataset**

In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age":[22,25,30,28,35],
    "Salary":[50000,70000,90000,80000,120000],
    "Department":["HR","IT","IT","Finance","HR"]
})
df

     Name  Age  Salary Department
0     Ali   22   50000         HR
1    Sara   25   70000         IT
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR

**1. Creating New Columns**

In [5]:
df["Bonus"] = df["Salary"]*0.1

In [6]:
df

     Name  Age  Salary Department    Bonus
0     Ali   22   50000         HR   5000.0
1    Sara   25   70000         IT   7000.0
2   Ahmed   30   90000         IT   9000.0
3  Ayesha   28   80000    Finance   8000.0
4   Bilal   35  120000         HR  12000.0

This is vectorized computation. No loops involved!

**2. map()**

In [7]:
department={
    "HR" : "Human Resource"
}
df["Department"] = df["Department"].map(department)

In [8]:
df

     Name  Age  Salary      Department    Bonus
0     Ali   22   50000  Human Resource   5000.0
1    Sara   25   70000             NaN   7000.0
2   Ahmed   30   90000             NaN   9000.0
3  Ayesha   28   80000             NaN   8000.0
4   Bilal   35  120000  Human Resource  12000.0

Notice that the missing keys become NaN using map()\
Let's create the dataset again and use another function that doesn't affect the unmatched keys.

In [9]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age":[22,25,30,28,35],
    "Salary":[50000,70000,90000,80000,120000],
    "Department":["HR","IT","IT","Finance","HR"]
})
df["Bonus"] = df["Salary"]*0.1
df

     Name  Age  Salary Department    Bonus
0     Ali   22   50000         HR   5000.0
1    Sara   25   70000         IT   7000.0
2   Ahmed   30   90000         IT   9000.0
3  Ayesha   28   80000    Finance   8000.0
4   Bilal   35  120000         HR  12000.0

That very function is discussed below:

**3. replace()**

In [10]:
df["Department"] = df["Department"].replace({
    "HR" : "Human Resources"
}
)
df

     Name  Age  Salary       Department    Bonus
0     Ali   22   50000  Human Resources   5000.0
1    Sara   25   70000               IT   7000.0
2   Ahmed   30   90000               IT   9000.0
3  Ayesha   28   80000          Finance   8000.0
4   Bilal   35  120000  Human Resources  12000.0

Notice the unmatched keys don't become NaN. Replace() is more flexible whereas map() is faster for pure mapping.

In [11]:
df["Department"] = df["Department"].replace({
    "IT" : "Information Technology"
}
)
df

     Name  Age  Salary              Department    Bonus
0     Ali   22   50000         Human Resources   5000.0
1    Sara   25   70000  Information Technology   7000.0
2   Ahmed   30   90000  Information Technology   9000.0
3  Ayesha   28   80000                 Finance   8000.0
4   Bilal   35  120000         Human Resources  12000.0

**4. apply()**

used to apply a custom function to every value

In [12]:
def age_category(age):
    if age<30:
        return "Young"
    return "Senior"
df["Category"] = df["Age"].apply(age_category)

In [13]:
df

     Name  Age  Salary              Department    Bonus Category
0     Ali   22   50000         Human Resources   5000.0    Young
1    Sara   25   70000  Information Technology   7000.0    Young
2   Ahmed   30   90000  Information Technology   9000.0   Senior
3  Ayesha   28   80000                 Finance   8000.0    Young
4   Bilal   35  120000         Human Resources  12000.0   Senior

Lambda Functions : Same result, but compact logic

In [14]:
df["Category"] = df["Age"].apply(
    lambda x: "Young" if x < 30 else "Senior"
)

In [15]:
df

     Name  Age  Salary              Department    Bonus Category
0     Ali   22   50000         Human Resources   5000.0    Young
1    Sara   25   70000  Information Technology   7000.0    Young
2   Ahmed   30   90000  Information Technology   9000.0   Senior
3  Ayesha   28   80000                 Finance   8000.0    Young
4   Bilal   35  120000         Human Resources  12000.0   Senior

**When not to use apply()**\
If vectorized operation for something exist, don't use apply()\
In case, there's no vectorized operation for intended operation, use apply()

**5. np.where()**

In [16]:
df["HighIncome"] = np.where(
    df["Salary"]>80000,
    "Yes",
    "No"
)

In [17]:
df

     Name  Age  Salary              Department    Bonus Category HighIncome
0     Ali   22   50000         Human Resources   5000.0    Young         No
1    Sara   25   70000  Information Technology   7000.0    Young         No
2   Ahmed   30   90000  Information Technology   9000.0   Senior        Yes
3  Ayesha   28   80000                 Finance   8000.0    Young         No
4   Bilal   35  120000         Human Resources  12000.0   Senior        Yes

Multiple Conditions:

In [19]:
df["Level"] = np.where(
    df["Salary"]>100000,
    "Gold",
    np.where(
        df["Salary"]>70000,
        "Silver",
        "Bronze"
    )
)
df

,Name,Age,Salary,Department,Bonus,Category,HighIncome,Level
0,Ali,22,50000,Human Resources,5000.0,Young,No,Bronze
1,Sara,25,70000,Information Technology,7000.0,Young,No,Bronze
2,Ahmed,30,90000,Information Technology,9000.0,Senior,Yes,Silver
3,Ayesha,28,80000,Finance,8000.0,Young,No,Silver
4,Bilal,35,120000,Human Resources,12000.0,Senior,Yes,Gold

**6. cut()**\
Used to categorize continuous data

In [21]:
bins = [18,25,35,50]
labels = [
    "Young Adult",
    "Adult",
    "Middle Age",
]
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins,
    labels=labels
)
df

,Name,Age,Salary,Department,Bonus,Category,HighIncome,Level,AgeGroup
0,Ali,22,50000,Human Resources,5000.0,Young,No,Bronze,Young Adult
1,Sara,25,70000,Information Technology,7000.0,Young,No,Bronze,Young Adult
2,Ahmed,30,90000,Information Technology,9000.0,Senior,Yes,Silver,Adult
3,Ayesha,28,80000,Finance,8000.0,Young,No,Silver,Adult
4,Bilal,35,120000,Human Resources,12000.0,Senior,Yes,Gold,Adult

**Why Businesses Use This**
Instead of:\
Customer Age = 31

Businesses prefer:\
Customer Segment = Adult

Much easier to analyze.

**7. qcut()**\
Difference:\
cut() : Width of bins specified\
qcut() : Number of entries per bin specified

In [22]:
df["SalaryLevel"] = pd.qcut(
    df["Salary"],
    q=3,
    labels=["Low","Medium","High"]
)
df

,Name,Age,Salary,Department,Bonus,Category,HighIncome,Level,AgeGroup,SalaryLevel
0,Ali,22,50000,Human Resources,5000.0,Young,No,Bronze,Young Adult,Low
1,Sara,25,70000,Information Technology,7000.0,Young,No,Bronze,Young Adult,Low
2,Ahmed,30,90000,Information Technology,9000.0,Senior,Yes,Silver,Adult,High
3,Ayesha,28,80000,Finance,8000.0,Young,No,Silver,Adult,Medium
4,Bilal,35,120000,Human Resources,12000.0,Senior,Yes,Gold,Adult,High

Very useful for:\
Customer segmentation\
Risk levels\
Marketing campaigns

**8. assign()**

In [23]:
df = df.assign(
    Bonus = df["Salary"]*0.1,
    Tax = df["Salary"]*0.2
)
df

,Name,Age,Salary,Department,Bonus,Category,HighIncome,Level,AgeGroup,SalaryLevel,Tax
0,Ali,22,50000,Human Resources,5000.0,Young,No,Bronze,Young Adult,Low,10000.0
1,Sara,25,70000,Information Technology,7000.0,Young,No,Bronze,Young Adult,Low,14000.0
2,Ahmed,30,90000,Information Technology,9000.0,Senior,Yes,Silver,Adult,High,18000.0
3,Ayesha,28,80000,Finance,8000.0,Young,No,Silver,Adult,Medium,16000.0
4,Bilal,35,120000,Human Resources,12000.0,Senior,Yes,Gold,Adult,High,24000.0

This becomes powerful in method chaining later