# <center>Time Series and DateTime Mastery

**Why DateTime Matters**\
Real-world datasets almost always contain:\
Order Date\
Transaction Time\
Login Time\
Registration Date\
Purchase Timestamp\
Delivery Date\
Sensor Timestamp\
Stock Market Timestamp

Your job is often:\
Revenue per month\
Users per week\
Sales growth per quarter\
Rolling average\
Moving windows\
Time-based filtering\
This entire phase teaches that.

**Dataset**

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Date":[
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05"
    ],
    "Sales":[
        100,
        120,
        110,
        150,
        130
    ]
})
df

         Date  Sales
0  2025-01-01    100
1  2025-01-02    120
2  2025-01-03    110
3  2025-01-04    150
4  2025-01-05    130

**1. Converting Strings to DateTime**

In [3]:
print(df["Date"].dtype)

object

This implies these are just strings\
**Solution**

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

In [7]:
print(df["Date"].dtype)

datetime64[ns]

Now, Python understands Years, Months, Days, Hours, Minutes, Seconds

**2. The .dt Accessor**\
Once a column becomes DateTime:

In [8]:
df["Date"].dt

unlocks many features.

Extract Year:

In [9]:
df["Year"] = df["Date"].dt.year

In [10]:
df

        Date  Sales  Year
0 2025-01-01    100  2025
1 2025-01-02    120  2025
2 2025-01-03    110  2025
3 2025-01-04    150  2025
4 2025-01-05    130  2025

Extract Month:

In [11]:
df["Month"] = df["Date"].dt.month

In [12]:
df

        Date  Sales  Year  Month
0 2025-01-01    100  2025      1
1 2025-01-02    120  2025      1
2 2025-01-03    110  2025      1
3 2025-01-04    150  2025      1
4 2025-01-05    130  2025      1

Extract Day:

In [13]:
df["Day"] = df["Date"].dt.day

In [14]:
df

        Date  Sales  Year  Month  Day
0 2025-01-01    100  2025      1    1
1 2025-01-02    120  2025      1    2
2 2025-01-03    110  2025      1    3
3 2025-01-04    150  2025      1    4
4 2025-01-05    130  2025      1    5

Extract month name:

In [15]:
df["Month Name"] = df["Date"].dt.month_name()

In [16]:
df

        Date  Sales  Year  Month  Day Month Name
0 2025-01-01    100  2025      1    1    January
1 2025-01-02    120  2025      1    2    January
2 2025-01-03    110  2025      1    3    January
3 2025-01-04    150  2025      1    4    January
4 2025-01-05    130  2025      1    5    January

In [17]:
df["Weekday Name"] = df["Date"].dt.day_name()

In [18]:
df

        Date  Sales  Year  Month  Day Month Name Weekday Name
0 2025-01-01    100  2025      1    1    January    Wednesday
1 2025-01-02    120  2025      1    2    January     Thursday
2 2025-01-03    110  2025      1    3    January       Friday
3 2025-01-04    150  2025      1    4    January     Saturday
4 2025-01-05    130  2025      1    5    January       Sunday

**3. Filtering By Dates**

In [19]:
df[
    df["Date"]>"2025-01-03"
    ]

        Date  Sales  Year  Month  Day Month Name Weekday Name
3 2025-01-04    150  2025      1    4    January     Saturday
4 2025-01-05    130  2025      1    5    January       Sunday

**4. Setting Date as Index**

In [20]:
df = df.set_index("Date")

In [21]:
df

            Sales  Year  Month  Day Month Name Weekday Name
Date
2025-01-01    100  2025      1    1    January    Wednesday
2025-01-02    120  2025      1    2    January     Thursday
2025-01-03    110  2025      1    3    January       Friday
2025-01-04    150  2025      1    4    January     Saturday
2025-01-05    130  2025      1    5    January       Sunday

In [23]:
df.loc["2025-01-03"]

Sales               110
Year               2025
Month                 1
Day                   3
Month Name      January
Weekday Name     Friday
Name: 2025-01-03 00:00:00, dtype: object

**5. Partial String Indexing**

Entire Month:

In [24]:
df.loc["2025-01"]

            Sales  Year  Month  Day Month Name Weekday Name
Date
2025-01-01    100  2025      1    1    January    Wednesday
2025-01-02    120  2025      1    2    January     Thursday
2025-01-03    110  2025      1    3    January       Friday
2025-01-04    150  2025      1    4    January     Saturday
2025-01-05    130  2025      1    5    January       Sunday

This means all dates inside January 2025

Entire Year:

In [26]:
df.loc["2025"]

            Sales  Year  Month  Day Month Name Weekday Name
Date
2025-01-01    100  2025      1    1    January    Wednesday
2025-01-02    120  2025      1    2    January     Thursday
2025-01-03    110  2025      1    3    January       Friday
2025-01-04    150  2025      1    4    January     Saturday
2025-01-05    130  2025      1    5    January       Sunday

Everything from 2025

**6. Date Ranges**

Generate dates:

In [30]:
pd.date_range(
    start = "2025-01-02",
    periods = 5
)

DatetimeIndex(['2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
               '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

Custom Frequency

Monthly:

In [34]:
pd.date_range(
    start = "2025-02",
    periods = 6,
    freq = "ME"
)

DatetimeIndex(['2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
               '2025-06-30', '2025-07-31'],
              dtype='datetime64[ns]', freq='ME')

Common Frequencies\
Code	Meaning\
D-->Daily\
W-->Weekly\
M-->Month End\
MS-->Month Start\
Q-->Quarterly\
Y-->Year End\
H-->Hourly\
min-->Minutes\
S-->Seconds

**7. Resampling**\
This is a groupby for time

Monthly Sales:

In [38]:
print(df.resample(
    "ME"
).sum())

            Sales   Year  Month  Day                           Month Name  \
Date
2025-01-31    610  10125      5   15  JanuaryJanuaryJanuaryJanuaryJanuary

                                     Weekday Name
Date
2025-01-31  WednesdayThursdayFridaySaturdaySunday

Example:

In [39]:
dates = pd.date_range(
    "2025-01-01",
    periods=60
)
sales = np.random.randint(
    100,
    200,
    60
)
df = pd.DataFrame({
    "Sales":sales
},index = dates)

In [40]:
df

            Sales
2025-01-01    100
2025-01-02    121
2025-01-03    107
2025-01-04    104
2025-01-05    191
2025-01-06    127
2025-01-07    173
2025-01-08    151
2025-01-09    134
2025-01-10    135
2025-01-11    161
2025-01-12    160
2025-01-13    165
2025-01-14    141
2025-01-15    177
2025-01-16    100
2025-01-17    152
2025-01-18    144
2025-01-19    135
2025-01-20    196
2025-01-21    159
2025-01-22    109
2025-01-23    172
2025-01-24    143
2025-01-25    137
2025-01-26    178
2025-01-27    135
2025-01-28    128
2025-01-29    128
2025-01-30    134
2025-01-31    173
2025-02-01    133
2025-02-02    147
2025-02-03    119
2025-02-04    170
2025-02-05    165
2025-02-06    130
2025-02-07    143
2025-02-08    190
2025-02-09    174
2025-02-10    186
2025-02-11    111
2025-02-12    160
2025-02-13    104
2025-02-14    125
2025-02-15    140
2025-02-16    133
2025-02-17    173
2025-02-18    143
2025-02-19    196
2025-02-20    135
2025-02-21    192
2025-02-22    153
2025-02-23    178
2025-02-24    138
2025-02-25    182
2025-02-26    184
2025-02-27    121
2025-02-28    191
2025-03-01    116

Monthly Totals:

In [41]:
df.resample(
    "ME"
).sum()

            Sales
2025-01-31   4470
2025-02-28   4316
2025-03-31    116

Monthly Averages:

In [42]:
df.resample(
    "ME"
).mean()

                 Sales
2025-01-31  144.193548
2025-02-28  154.142857
2025-03-31  116.000000

Intuition:\
groupby() --> categories\
resample() --> Time periods

**8. Rolling Windows**

Question: Average sales over the last 3 days?

In [43]:
df["Rolling_3"] = df["Sales"].rolling(3).mean()

In [45]:
df

            Sales   Rolling_3
2025-01-01    100         NaN
2025-01-02    121         NaN
2025-01-03    107  109.333333
2025-01-04    104  110.666667
2025-01-05    191  134.000000
2025-01-06    127  140.666667
2025-01-07    173  163.666667
2025-01-08    151  150.333333
2025-01-09    134  152.666667
2025-01-10    135  140.000000
2025-01-11    161  143.333333
2025-01-12    160  152.000000
2025-01-13    165  162.000000
2025-01-14    141  155.333333
2025-01-15    177  161.000000
2025-01-16    100  139.333333
2025-01-17    152  143.000000
2025-01-18    144  132.000000
2025-01-19    135  143.666667
2025-01-20    196  158.333333
2025-01-21    159  163.333333
2025-01-22    109  154.666667
2025-01-23    172  146.666667
2025-01-24    143  141.333333
2025-01-25    137  150.666667
2025-01-26    178  152.666667
2025-01-27    135  150.000000
2025-01-28    128  147.000000
2025-01-29    128  130.333333
2025-01-30    134  130.000000
2025-01-31    173  145.000000
2025-02-01    133  146.666667
2025-02-02    147  151.000000
2025-02-03    119  133.000000
2025-02-04    170  145.333333
2025-02-05    165  151.333333
2025-02-06    130  155.000000
2025-02-07    143  146.000000
2025-02-08    190  154.333333
2025-02-09    174  169.000000
2025-02-10    186  183.333333
2025-02-11    111  157.000000
2025-02-12    160  152.333333
2025-02-13    104  125.000000
2025-02-14    125  129.666667
2025-02-15    140  123.000000
2025-02-16    133  132.666667
2025-02-17    173  148.666667
2025-02-18    143  149.666667
2025-02-19    196  170.666667
2025-02-20    135  158.000000
2025-02-21    192  174.333333
2025-02-22    153  160.000000
2025-02-23    178  174.333333
2025-02-24    138  156.333333
2025-02-25    182  166.000000
2025-02-26    184  168.000000
2025-02-27    121  162.333333
2025-02-28    191  165.333333
2025-03-01    116  142.666667

Intuition:\
Takes\
current day + previous 2 days = 3 days in total\
Average\
This is called:\
Moving Average\
Because it shows how the average of immediate 3 days moves or changes with every single day

**9. Expanding Windows**\
rolling(n) --> Last n values\
expanding() --> Everything so far

In [49]:
df["Running Average"] = df[
    "Sales"
    ].expanding().mean()

In [50]:
df

            Sales   Rolling_3  Running Average
2025-01-01    100         NaN       100.000000
2025-01-02    121         NaN       110.500000
2025-01-03    107  109.333333       109.333333
2025-01-04    104  110.666667       108.000000
2025-01-05    191  134.000000       124.600000
2025-01-06    127  140.666667       125.000000
2025-01-07    173  163.666667       131.857143
2025-01-08    151  150.333333       134.250000
2025-01-09    134  152.666667       134.222222
2025-01-10    135  140.000000       134.300000
2025-01-11    161  143.333333       136.727273
2025-01-12    160  152.000000       138.666667
2025-01-13    165  162.000000       140.692308
2025-01-14    141  155.333333       140.714286
2025-01-15    177  161.000000       143.133333
2025-01-16    100  139.333333       140.437500
2025-01-17    152  143.000000       141.117647
2025-01-18    144  132.000000       141.277778
2025-01-19    135  143.666667       140.947368
2025-01-20    196  158.333333       143.700000
2025-01-21    159  163.333333       144.428571
2025-01-22    109  154.666667       142.818182
2025-01-23    172  146.666667       144.086957
2025-01-24    143  141.333333       144.041667
2025-01-25    137  150.666667       143.760000
2025-01-26    178  152.666667       145.076923
2025-01-27    135  150.000000       144.703704
2025-01-28    128  147.000000       144.107143
2025-01-29    128  130.333333       143.551724
2025-01-30    134  130.000000       143.233333
2025-01-31    173  145.000000       144.193548
2025-02-01    133  146.666667       143.843750
2025-02-02    147  151.000000       143.939394
2025-02-03    119  133.000000       143.205882
2025-02-04    170  145.333333       143.971429
2025-02-05    165  151.333333       144.555556
2025-02-06    130  155.000000       144.162162
2025-02-07    143  146.000000       144.131579
2025-02-08    190  154.333333       145.307692
2025-02-09    174  169.000000       146.025000
2025-02-10    186  183.333333       147.000000
2025-02-11    111  157.000000       146.142857
2025-02-12    160  152.333333       146.465116
2025-02-13    104  125.000000       145.500000
2025-02-14    125  129.666667       145.044444
2025-02-15    140  123.000000       144.934783
2025-02-16    133  132.666667       144.680851
2025-02-17    173  148.666667       145.270833
2025-02-18    143  149.666667       145.224490
2025-02-19    196  170.666667       146.240000
2025-02-20    135  158.000000       146.019608
2025-02-21    192  174.333333       146.903846
2025-02-22    153  160.000000       147.018868
2025-02-23    178  174.333333       147.592593
2025-02-24    138  156.333333       147.418182
2025-02-25    182  166.000000       148.035714
2025-02-26    184  168.000000       148.666667
2025-02-27    121  162.333333       148.189655
2025-02-28    191  165.333333       148.915254
2025-03-01    116  142.666667       148.366667

**10. Shifting**

In [51]:
df["Yesterday"] = df[
    "Sales"
    ].shift(1)

In [52]:
df

            Sales   Rolling_3  Running Average  Yesterday
2025-01-01    100         NaN       100.000000        NaN
2025-01-02    121         NaN       110.500000      100.0
2025-01-03    107  109.333333       109.333333      121.0
2025-01-04    104  110.666667       108.000000      107.0
2025-01-05    191  134.000000       124.600000      104.0
2025-01-06    127  140.666667       125.000000      191.0
2025-01-07    173  163.666667       131.857143      127.0
2025-01-08    151  150.333333       134.250000      173.0
2025-01-09    134  152.666667       134.222222      151.0
2025-01-10    135  140.000000       134.300000      134.0
2025-01-11    161  143.333333       136.727273      135.0
2025-01-12    160  152.000000       138.666667      161.0
2025-01-13    165  162.000000       140.692308      160.0
2025-01-14    141  155.333333       140.714286      165.0
2025-01-15    177  161.000000       143.133333      141.0
2025-01-16    100  139.333333       140.437500      177.0
2025-01-17    152  143.000000       141.117647      100.0
2025-01-18    144  132.000000       141.277778      152.0
2025-01-19    135  143.666667       140.947368      144.0
2025-01-20    196  158.333333       143.700000      135.0
2025-01-21    159  163.333333       144.428571      196.0
2025-01-22    109  154.666667       142.818182      159.0
2025-01-23    172  146.666667       144.086957      109.0
2025-01-24    143  141.333333       144.041667      172.0
2025-01-25    137  150.666667       143.760000      143.0
2025-01-26    178  152.666667       145.076923      137.0
2025-01-27    135  150.000000       144.703704      178.0
2025-01-28    128  147.000000       144.107143      135.0
2025-01-29    128  130.333333       143.551724      128.0
2025-01-30    134  130.000000       143.233333      128.0
2025-01-31    173  145.000000       144.193548      134.0
2025-02-01    133  146.666667       143.843750      173.0
2025-02-02    147  151.000000       143.939394      133.0
2025-02-03    119  133.000000       143.205882      147.0
2025-02-04    170  145.333333       143.971429      119.0
2025-02-05    165  151.333333       144.555556      170.0
2025-02-06    130  155.000000       144.162162      165.0
2025-02-07    143  146.000000       144.131579      130.0
2025-02-08    190  154.333333       145.307692      143.0
2025-02-09    174  169.000000       146.025000      190.0
2025-02-10    186  183.333333       147.000000      174.0
2025-02-11    111  157.000000       146.142857      186.0
2025-02-12    160  152.333333       146.465116      111.0
2025-02-13    104  125.000000       145.500000      160.0
2025-02-14    125  129.666667       145.044444      104.0
2025-02-15    140  123.000000       144.934783      125.0
2025-02-16    133  132.666667       144.680851      140.0
2025-02-17    173  148.666667       145.270833      133.0
2025-02-18    143  149.666667       145.224490      173.0
2025-02-19    196  170.666667       146.240000      143.0
2025-02-20    135  158.000000       146.019608      196.0
2025-02-21    192  174.333333       146.903846      135.0
2025-02-22    153  160.000000       147.018868      192.0
2025-02-23    178  174.333333       147.592593      153.0
2025-02-24    138  156.333333       147.418182      178.0
2025-02-25    182  166.000000       148.035714      138.0
2025-02-26    184  168.000000       148.666667      182.0
2025-02-27    121  162.333333       148.189655      184.0
2025-02-28    191  165.333333       148.915254      121.0
2025-03-01    116  142.666667       148.366667      191.0

Difference between Days:

In [54]:
df["Difference"] = df[
    "Sales"
    ].diff()

In [55]:
df

            Sales   Rolling_3  Running Average  Yesterday  Difference
2025-01-01    100         NaN       100.000000        NaN         NaN
2025-01-02    121         NaN       110.500000      100.0        21.0
2025-01-03    107  109.333333       109.333333      121.0       -14.0
2025-01-04    104  110.666667       108.000000      107.0        -3.0
2025-01-05    191  134.000000       124.600000      104.0        87.0
2025-01-06    127  140.666667       125.000000      191.0       -64.0
2025-01-07    173  163.666667       131.857143      127.0        46.0
2025-01-08    151  150.333333       134.250000      173.0       -22.0
2025-01-09    134  152.666667       134.222222      151.0       -17.0
2025-01-10    135  140.000000       134.300000      134.0         1.0
2025-01-11    161  143.333333       136.727273      135.0        26.0
2025-01-12    160  152.000000       138.666667      161.0        -1.0
2025-01-13    165  162.000000       140.692308      160.0         5.0
2025-01-14    141  155.333333       140.714286      165.0       -24.0
2025-01-15    177  161.000000       143.133333      141.0        36.0
2025-01-16    100  139.333333       140.437500      177.0       -77.0
2025-01-17    152  143.000000       141.117647      100.0        52.0
2025-01-18    144  132.000000       141.277778      152.0        -8.0
2025-01-19    135  143.666667       140.947368      144.0        -9.0
2025-01-20    196  158.333333       143.700000      135.0        61.0
2025-01-21    159  163.333333       144.428571      196.0       -37.0
2025-01-22    109  154.666667       142.818182      159.0       -50.0
2025-01-23    172  146.666667       144.086957      109.0        63.0
2025-01-24    143  141.333333       144.041667      172.0       -29.0
2025-01-25    137  150.666667       143.760000      143.0        -6.0
2025-01-26    178  152.666667       145.076923      137.0        41.0
2025-01-27    135  150.000000       144.703704      178.0       -43.0
2025-01-28    128  147.000000       144.107143      135.0        -7.0
2025-01-29    128  130.333333       143.551724      128.0         0.0
2025-01-30    134  130.000000       143.233333      128.0         6.0
2025-01-31    173  145.000000       144.193548      134.0        39.0
2025-02-01    133  146.666667       143.843750      173.0       -40.0
2025-02-02    147  151.000000       143.939394      133.0        14.0
2025-02-03    119  133.000000       143.205882      147.0       -28.0
2025-02-04    170  145.333333       143.971429      119.0        51.0
2025-02-05    165  151.333333       144.555556      170.0        -5.0
2025-02-06    130  155.000000       144.162162      165.0       -35.0
2025-02-07    143  146.000000       144.131579      130.0        13.0
2025-02-08    190  154.333333       145.307692      143.0        47.0
2025-02-09    174  169.000000       146.025000      190.0       -16.0
2025-02-10    186  183.333333       147.000000      174.0        12.0
2025-02-11    111  157.000000       146.142857      186.0       -75.0
2025-02-12    160  152.333333       146.465116      111.0        49.0
2025-02-13    104  125.000000       145.500000      160.0       -56.0
2025-02-14    125  129.666667       145.044444      104.0        21.0
2025-02-15    140  123.000000       144.934783      125.0        15.0
2025-02-16    133  132.666667       144.680851      140.0        -7.0
2025-02-17    173  148.666667       145.270833      133.0        40.0
2025-02-18    143  149.666667       145.224490      173.0       -30.0
2025-02-19    196  170.666667       146.240000      143.0        53.0
2025-02-20    135  158.000000       146.019608      196.0       -61.0
2025-02-21    192  174.333333       146.903846      135.0        57.0
2025-02-22    153  160.000000       147.018868      192.0       -39.0
2025-02-23    178  174.333333       147.592593      153.0        25.0
2025-02-24    138  156.333333       147.418182      178.0       -40.0
2025-02-25    182  166.000000       148.035714      138.0        44.0
2025-02-26    184  168.000000       148.666667      182.0         2.0
2025-02-27    121  162.333333       148.189655      184.0       -63.0
2025-02-28    191  165.333333       148.915254      121.0        70.0
2025-03-01    116  142.666667       148.366667      191.0       -75.0

Percentage Growth:

In [56]:
df["Growth"] = df["Sales"].pct_change()

In [57]:
df

,Sales,Rolling_3,Running Average,Yesterday,Difference,Growth
2025-01-01,100,NaN,100.000000,NaN,NaN,NaN
2025-01-02,121,NaN,110.500000,100.0,21.0,0.210000
2025-01-03,107,109.333333,109.333333,121.0,-14.0,-0.115702
2025-01-04,104,110.666667,108.000000,107.0,-3.0,-0.028037
2025-01-05,191,134.000000,124.600000,104.0,87.0,0.836538
2025-01-06,127,140.666667,125.000000,191.0,-64.0,-0.335079
2025-01-07,173,163.666667,131.857143,127.0,46.0,0.362205
2025-01-08,151,150.333333,134.250000,173.0,-22.0,-0.127168
2025-01-09,134,152.666667,134.222222,151.0,-17.0,-0.112583
2025-01-10,135,140.000000,134.300000,134.0,1.0,0.007463
2025-01-11,161,143.333333,136.727273,135.0,26.0,0.192593
2025-01-12,160,152.000000,138.666667,161.0,-1.0,-0.006211
2025-01-13,165,162.000000,140.692308,160.0,5.0,0.031250
2025-01-14,141,155.333333,140.714286,165.0,-24.0,-0.145455
2025-01-15,177,161.000000,143.133333,141.0,36.0,0.255319
2025-01-16,100,139.333333,140.437500,177.0,-77.0,-0.435028
2025-01-17,152,143.000000,141.117647,100.0,52.0,0.520000
2025-01-18,144,132.000000,141.277778,152.0,-8.0,-0.052632
2025-01-19,135,143.666667,140.947368,144.0,-9.0,-0.062500
2025-01-20,196,158.333333,143.700000,135.0,61.0,0.451852
2025-01-21,159,163.333333,144.428571,196.0,-37.0,-0.188776
2025-01-22,109,154.666667,142.818182,159.0,-50.0,-0.314465
2025-01-23,172,146.666667,144.086957,109.0,63.0,0.577982
2025-01-24,143,141.333333,144.041667,172.0,-29.0,-0.168605
2025-01-25,137,150.666667,143.760000,143.0,-6.0,-0.041958
2025-01-26,178,152.666667,145.076923,137.0,41.0,0.299270
2025-01-27,135,150.000000,144.703704,178.0,-43.0,-0.241573
2025-01-28,128,147.000000,144.107143,135.0,-7.0,-0.051852
2025-01-29,128,130.333333,143.551724,128.0,0.0,0.000000
2025-01-30,134,130.000000,143.233333,128.0,6.0,0.046875
2025-01-31,173,145.000000,144.193548,134.0,39.0,0.291045
2025-02-01,133,146.666667,143.843750,173.0,-40.0,-0.231214
2025-02-02,147,151.000000,143.939394,133.0,14.0,0.105263
2025-02-03,119,133.000000,143.205882,147.0,-28.0,-0.190476
2025-02-04,170,145.333333,143.971429,119.0,51.0,0.428571
2025-02-05,165,151.333333,144.555556,170.0,-5.0,-0.029412
2025-02-06,130,155.000000,144.162162,165.0,-35.0,-0.212121
2025-02-07,143,146.000000,144.131579,130.0,13.0,0.100000
2025-02-08,190,154.333333,145.307692,143.0,47.0,0.328671
2025-02-09,174,169.000000,146.025000,190.0,-16.0,-0.084211
2025-02-10,186,183.333333,147.000000,174.0,12.0,0.068966
2025-02-11,111,157.000000,146.142857,186.0,-75.0,-0.403226
2025-02-12,160,152.333333,146.465116,111.0,49.0,0.441441
2025-02-13,104,125.000000,145.500000,160.0,-56.0,-0.350000
2025-02-14,125,129.666667,145.044444,104.0,21.0,0.201923
2025-02-15,140,123.000000,144.934783,125.0,15.0,0.120000
2025-02-16,133,132.666667,144.680851,140.0,-7.0,-0.050000
2025-02-17,173,148.666667,145.270833,133.0,40.0,0.300752
2025-02-18,143,149.666667,145.224490,173.0,-30.0,-0.173410
2025-02-19,196,170.666667,146.240000,143.0,53.0,0.370629
2025-02-20,135,158.000000,146.019608,196.0,-61.0,-0.311224
2025-02-21,192,174.333333,146.903846,135.0,57.0,0.422222
2025-02-22,153,160.000000,147.018868,192.0,-39.0,-0.203125
2025-02-23,178,174.333333,147.592593,153.0,25.0,0.163399
2025-02-24,138,156.333333,147.418182,178.0,-40.0,-0.224719
2025-02-25,182,166.000000,148.035714,138.0,44.0,0.318841
2025-02-26,184,168.000000,148.666667,182.0,2.0,0.010989
2025-02-27,121,162.333333,148.189655,184.0,-63.0,-0.342391
2025-02-28,191,165.333333,148.915254,121.0,70.0,0.578512
2025-03-01,116,142.666667,148.366667,191.0,-75.0,-0.392670

All of these are extremely important in finance