# <center>PANDAS

#### Why Pandas Exists

Imagine your NumPy dataset:

In [3]:
import numpy as np

data = np.array([
    [22,50000,80],
    [25,70000,60],
    [30,90000,90]
])

**Questions Arise:**\
What does column 0 mean?\
What does column 1 mean?\
What does column 2 mean?\
You need documentation or memory.

Pandas solves this.

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Age":[22,25,30],
    "Salary":[50000,70000,90000],
    "Spending":[80,60,90]
})

Now:

Age
Salary
Spending

are explicitly labeled.

## <center> Series and DataFrames Fundamentals</center>

**1. Series**\
**Think:**\
Series = One Column\
**Equivalent to:**\
NumPy 1D Array\
+\
Labels

In [3]:
import pandas as pd
ages = pd.Series([22,25,30])
ages

0    22
1    25
2    30
dtype: int64

Notice that indices also appear along with the series, and the datatype of the series too

**Anatomy of Series**\
Series contains\
a) Values

In [4]:
ages.values

array([22, 25, 30])

b) Index

In [6]:
ages.index

RangeIndex(start=0, stop=3, step=1)

c) DataType

In [8]:
ages.dtype

dtype('int64')

d) Custom Index: Indexes do not necessarily have to be numbers

In [10]:
ages = pd.Series(
    [22,25,30],
    index = ['Ali','Sara','Ahmed']
)
ages

Ali      22
Sara     25
Ahmed    30
dtype: int64

In [11]:
ages['Sara']

np.int64(25)

This is the foundation of Pandas.

**2) DataFrames:**
**Think:**\
DataFrame = Multiple Series Together

In [12]:
df = pd.DataFrame({
    "Name": ["Ali","Sara","Ahmed"],
    "Age": [22,25,30],
    "Salary": [50000,70000,90000]
})
df

    Name  Age  Salary
0    Ali   22   50000
1   Sara   25   70000
2  Ahmed   30   90000

**Anatomy of a DataFrame**\
Every DataFrame contains:\
Rows\
Columns\
Index\
Values\
Datatypes

**Ways to Create DataFrames**\
a) DataFrame from a NumPy Array:

In [14]:
data = np.array([
    [22,50000],
    [25,70000],
    [30,90000]
])
df = pd.DataFrame(
    data,
    columns=["Age","Salary"]
)
df

   Age  Salary
0   22   50000
1   25   70000
2   30   90000

b) DataFrame from a Dictionary: (Most Common)

In [15]:
df = pd.DataFrame({
    "Age":[22,25,30],
    "Salary":[50000,70000,90000]
})
df

   Age  Salary
0   22   50000
1   25   70000
2   30   90000

c) DataFrame from a list of dictionaries: (Very common in APIs)

In [5]:
df = pd.DataFrame([
    {"Age":22,"Salary":50000},
    {"Age":25,"Salary":70000},
    {"Age":30,"Salary":90000}
])
df

   Age  Salary
0   22   50000
1   25   70000
2   30   90000

**Essential Attributes**\
a) Shape

In [8]:
df.shape

(3, 2)

b) Columns

In [9]:
df.columns

Index(['Age', 'Salary'], dtype='object')

c) Index

In [ ]:
df.index

d) dtypes

In [6]:
df.dtypes

Age       int64
Salary    int64
dtype: object

e) ndim

In [7]:
df.ndim

2

f) values

In [8]:
df.values

array([[   22, 50000],
       [   25, 70000],
       [   30, 90000]])

g) size

In [9]:
df.size

6

**info()**\
One of the most important Pandas functions.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     3 non-null      int64
 1   Salary  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

Industry analysts run this almost immediately after loading data.

**describe()**\
Quick statistical summary.

In [12]:
df.describe()

             Age   Salary
count   3.000000      3.0
mean   25.666667  70000.0
std     4.041452  20000.0
min    22.000000  50000.0
25%    23.500000  60000.0
50%    25.000000  70000.0
75%    27.500000  80000.0
max    30.000000  90000.0

### <center>Practice Tasks

**Problem 1**\
Create a Series containing:\
10\
20\
30\
40\
50\
**Print:**\
.values\
.index\
.dtype

In [14]:
s = pd.Series([10,20,30,40,50])
print(s.values)
print(s.index)
print(s.dtype)

[10 20 30 40 50]
RangeIndex(start=0, stop=5, step=1)
int64

**Problem 2**\
Create a Series with custom index:\
Math\
Physics\
Chemistry\
**Values:**\
85\
90\
88\
Retrieve Physics marks.

In [18]:
s = pd.Series(
    [85,90,88],
    index = ["Math","Physics","Chemistry"]
)
s["Physics"]

np.int64(90)

**Problem 3**\
Create a DataFrame containing:\
Name\
Age\
Salary\
for 5 employees.\
**Print:**\
shape\
columns\
dtypes

In [20]:
df = pd.DataFrame({
    "Name":['Ali','Eman','Ahmed','Umar','Saad'],
    "Age":[22,24,25,25,26],
    "Salary":[25000,27000,27000,35000,28000]
})
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)

    Name  Age  Salary
0    Ali   22   25000
1   Eman   24   27000
2  Ahmed   25   27000
3   Umar   25   35000
4   Saad   26   28000
(5, 3)
Index(['Name', 'Age', 'Salary'], dtype='object')
Name      object
Age        int64
Salary     int64
dtype: object

**Problem 4**\
Create a DataFrame from a NumPy array.\
**Columns:**\
Age\
Salary\
Experience

In [24]:
data = np.array([
    [20,25000,5],
    [22,29000,7],
    [21,27000,6]
])
df = pd.DataFrame(
    data,
    columns=["Age","Salary","Experience"]
)
df

   Age  Salary  Experience
0   20   25000           5
1   22   29000           7
2   21   27000           6

**Problem 5**\
Create a DataFrame from a list of dictionaries.\
**Store:**\
Product\
Price\
Quantity

In [25]:
store = pd.DataFrame(
    {"Product":"Toothpaste","Price":250,"Quantity":2},
    {"Product":"Toothbrush","Price":120,"Quantity":3},
    {"Product":"Soap","Price":80,"Quantity":1}
)
store

             Product  Price  Quantity
Product   Toothpaste    250         2
Price     Toothpaste    250         2
Quantity  Toothpaste    250         2

**Problem 6**\
**Find:**\
size\
ndim\
values\
for the DataFrame.

In [27]:
print(store.size)
print(store.ndim)
print(store.values)

9
2
[['Toothpaste' 250 2]
 ['Toothpaste' 250 2]
 ['Toothpaste' 250 2]]

**Problem 7**\
Create a student dataset with:\
StudentID\
Age\
Marks\
Attendance\
**Run:**\
info()\
describe()

In [28]:
student = pd.DataFrame({
    "ID":[21,22,23],
    "Age":[21,24,23],
    "Marks":[85,89,90],
    "Attendance":[98,92,75]
})
print(student.info())
print(student.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          3 non-null      int64
 1   Age         3 non-null      int64
 2   Marks       3 non-null      int64
 3   Attendance  3 non-null      int64
dtypes: int64(4)
memory usage: 228.0 bytes
None
         ID        Age      Marks  Attendance
count   3.0   3.000000   3.000000    3.000000
mean   22.0  22.666667  88.000000   88.333333
std     1.0   1.527525   2.645751   11.930353
min    21.0  21.000000  85.000000   75.000000
25%    21.5  22.000000  87.000000   83.500000
50%    22.0  23.000000  89.000000   92.000000
75%    22.5  23.500000  89.500000   95.000000
max    23.0  24.000000  90.000000   98.000000

**Problem 9**\
Create a DataFrame for:\
100 customers\
using NumPy random generation.\
**Columns:**\
CustomerID\
Age\
Salary\
SpendingScore\
**Inspect using:**\
shape\
info\
describe

In [35]:
cust_id = np.random.randint(0,11,5)
age = np.random.randint(18,29,5)
salary = np.random.randint(30000,100001,5)
spending_score = np.random.randint(45,99,5)
customers = np.column_stack((cust_id,age,salary,spending_score))
customer = pd.DataFrame(
    customers,
    columns=["Customer ID","Age","Salary","Spending Score"]
)
customer

   Customer ID  Age  Salary  Spending Score
0            5   23   48431              95
1            1   26   32747              88
2            4   18   89150              96
3            0   28   95725              47
4            9   28   65773              81