# <center>Advanced Input/Output (I/O)

**1. CSV Files**\
CSV(Comma-Separated Values) is by far the most common data format in Data Science.

**Reading a CSV**

In [3]:
import pandas as pd
df = pd.read_csv("customers.csv")
print(df)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

read_csv() is probably the single most-used Pandas function in industry

**Saving a CSV**

In [4]:
df.to_csv("output.csv")

This creates an extra column because Pandas always saves the index

Correct way:

In [7]:
df.to_csv(
    "output.csv",
    index=False
)

index=False avoids saving index as a column unless you explicitly want to save the index

**2. Selecting Specific Columns While Reading**\
Imagine a CSV with 12 columns but you want only three

Bad:

In [8]:
df = pd.read_csv("customers.csv")

Good:

In [9]:
df = pd.read_csv(
    "customers.csv",
    usecols=[
        "First Name",
        "Last Name",
        "City"
    ]
)

In [10]:
df

   First Name Last Name               City
0      Sheryl    Baxter       East Leonard
1     Preston    Lozano  East Jimmychester
2         Roy     Berry      Isabelborough
3       Linda     Olsen         Bensonview
4      Joanna    Bender     West Priscilla
..        ...       ...                ...
95       Karl     Greer       East Richard
96       Lynn  Atkinson       New Bradview
97       Fred    Guerra         Ortegaland
98     Yvonne    Farmer    Lake Elijahview
99   Clarence    Haynes          Judymouth

[100 rows x 3 columns]

**Benefits:**\
Faster\
Less RAM\
Cleaner\
Professional almost always use usecols for large datasets.

**3. Choosing DataTypes While Reading**

In [13]:
countries =  pd.read_csv(
    "customers.csv",
    usecols=["Country"],
    dtype={
        "Country":"category"
    }
)

In [16]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  100 non-null    category
dtypes: category(1)
memory usage: 2.9 KB

This is faster and more memory efficient than firstly loading a CSV and then changing the DataTypes of specific columns.

**4. Handling missing value during import**

Suppose your CSV contains:\
Salary\
50000\
NA\
Missing\
70000\
Tell Pandas these represent missing values

In [17]:
df = pd.read_csv(
    "customers.csv",
    na_values=[
        "NA",
        "Missing"
    ]
)

Now, the missing values become NaN and can be dealt with easily.

**5. Reading Large CSVs**\
Usage of chunks is the best option

In [18]:
chunks = pd.read_csv(
    "customers.csv",
    chunksize=10
)

In [20]:
print(chunks)

<pandas.io.parsers.readers.TextFileReader object at 0x00000278716B5E10>

In [22]:
for chunk in chunks:
    print(chunk["City"])

0         East Leonard
1    East Jimmychester
2        Isabelborough
3           Bensonview
4       West Priscilla
5        Chavezborough
6             Lake Ana
7              Kimport
8         Robersonstad
9           Elaineberg
Name: City, dtype: object
10         Shannonville
11          East Andrea
12    South Joannamouth
13             Jodyberg
14            Burchbury
15         Desireeshire
16    West Adriennestad
17          Lake Leslie
18           Harmonview
19           Jamesshire
Name: City, dtype: object
20           East Carly
21          South Alvin
22         Brittanyview
23        Veronicamouth
24           Bryanville
25          Kaitlyntown
26         Michealshire
27    South Marissatown
28         Acevedoville
29         North Harold
Name: City, dtype: object
30          West Samuel
31    Cunninghamborough
32        Port Annatown
33          New Kaitlyn
34     West Marthaburgh
35          East Teresa
36         South Hunter
37         South Walter
38            Poolefurt
39            West John
Name: City, dtype: object
40            West Darius
41          North Jimstad
42    East Rebekahborough
43             North Drew
44        Lake Lindaburgh
45          Gwendolynview
46          Zimmermanland
47         North Kerriton
48      North Eileenville
49        Port Sergiofort
Name: City, dtype: object
50       New Alberttown
51        South Jasmine
52            Cowanfort
53          New Deborah
54            Wallstown
55    Lake Ellenchester
56         Lake Whitney
57       East Jaredbury
58           Selenabury
59            Huangfort
Name: City, dtype: object
60       East Pennyshire
61    Port Jasminborough
62         West Kristine
63           South Julia
64          Helenborough
65            Lake Nancy
66            Georgeport
67      South Sophiaberg
68              Hartbury
69            Erikaville
Name: City, dtype: object
70            Nicolasfort
71       New Jasmineshire
72        East Summerstad
73            Skinnerport
74                Raystad
75             Colinhaven
76          West Reginald
77     Lake Sherryborough
78    Port Katherineville
79             Thomasland
Name: City, dtype: object
80            Coreybury
81       Lake Janiceton
82         East Clinton
83    South Joshuashire
84           New Glenda
85    North Jillianview
86            Lyonsberg
87    East Cristinabury
88           Thomasfurt
89       North Joeburgh
Name: City, dtype: object
90      Cassidychester
91    South Dannymouth
92        South Lonnie
93        Frankchester
94        Daisyborough
95        East Richard
96        New Bradview
97          Ortegaland
98     Lake Elijahview
99           Judymouth
Name: City, dtype: object

This is exactly how ETL pipelines work.

**6. Excel Files**

**Reading Excel**

In [27]:
df = pd.read_excel(
    "output.xlsx"
)

In [25]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

**Specific Sheet**

In [35]:
df = pd.read_excel(
    "output.xlsx",
    sheet_name="sheet1"
)

**Reading Multiple Sheets**

In [31]:
df = pd.read_excel(
    "output.xlsx",
    sheet_name=None
)

In [33]:
type(df)

dict

Keys --> Sheets\
Values --> DataFrames

**Saving Excel**

In [36]:
df.to_excel(
    "report.xlsx",
    index=False
)

**7. JSON Files**

**Reading JSON**

In [4]:
import pandas as pd
df = pd.read_json(
    "data.json"
)

In [5]:
df

,database_name,version,is_active,last_updated,users
0,users_test_environment,1.2,True,NaN,"{'id': 101, 'name': 'Alice Johnson', 'email': ..."
1,users_test_environment,1.2,True,NaN,"{'id': 102, 'name': 'Bob Smith', 'email': 'bob..."

**Saving JSON**

In [6]:
df.to_json(
    "employees.json"
)

**8. Parquet Files**\
**Reading Parquet**

In [9]:
df = pd.read_parquet(
    "employees.parquet"
)

**Writing**

In [11]:
df.to_parquet(
    "employees.parquet"
)

**9. SQL Databases**\
Usually the workflow is:\
Database --> Pandas --> Analysis --> Dashboard --> Machine Learning

In [ ]:
df = pd.read_sql(
    "SELECT * FROM employees",
    connection
)

Using a query:

In [ ]:
query = """
SELECT Name,
Salary
FROM employees
WHERE Salary > 70000
"""

df = pd.read_sql(
    query,
    connection
)

Save Back:

In [ ]:
df.to_sql(
    "employees",
    connection,
    if_exists="replace",
    index=False
)

**10. Reading from URLs**\
Pandas can directly read many online datasets

In [ ]:
df = pd.read_csv(
    "https://example.com/data.csv"
)

**11. Common Parameters You Should Know**

Read first 100 rows

In [13]:
pd.read_csv(
    "customers.csv",
    nrows=100
)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

Skip first few rows

In [14]:
pd.read_csv(
    "customers.csv",
    skiprows=5
)

,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
0,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
1,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
2,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
3,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
4,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
90,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
91,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
92,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
93,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
94,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

Different delimiter

In [ ]:
pd.read_csv(
    "data.csv",
    sep=";"
)

No header

In [15]:
pd.read_csv(
    "customers.csv",
    header=None
)

,0,1,2,3,4,5,6,7,8,9,10,11
0,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
2,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
3,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
4,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
97,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
98,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
99,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
100,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

Custom Column names

In [ ]:
pd.read_csv(
    "data.csv",
    names=[
        "ID",
        "Name",
        "Salary"
    ]
)