# <center>SQL Thinking with Pandas

This is extremely valuable because:

Data Scientists:\
SQL + Pandas

Data Analysts:\
SQL + Pandas

Data Engineers:\
SQL + Pandas

ML Engineers:\
SQL + Pandas

These two languages are deeply connected.

**The Big Idea:**\
SQL operates on TABLES\
Pandas operates on DataFrames

**Dataset**

In [27]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age":[22,25,30,28,35],
    "Salary":[50000,70000,90000,80000,120000],
    "Department":["HR","IT","IT","Finance","HR"]
})
df

     Name  Age  Salary Department
0     Ali   22   50000         HR
1    Sara   25   70000         IT
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR

**1. SELECT**\
**SQL**\
SELECT Name, Salary\
FROM Employees;

**Pandas**

In [3]:
df[["Name","Salary"]]

     Name  Salary
0     Ali   50000
1    Sara   70000
2   Ahmed   90000
3  Ayesha   80000
4   Bilal  120000

**2. WHERE**\
**SQL**\
SELECT *\
FROM Employees\
WHERE Salary > 80000;

**Pandas**

In [4]:
df[df["Salary"]>80000]

    Name  Age  Salary Department
2  Ahmed   30   90000         IT
4  Bilal   35  120000         HR

Multiple Conditions:\
**SQL**\
SELECT * FROM Employees\
WHERE Department='IT'\
AND Salary > 70000;

**Pandas**

In [5]:
df[
    (df["Department"]=="IT")
    &
    (df["Salary"]>70000)
    ]

    Name  Age  Salary Department
2  Ahmed   30   90000         IT

**3. ORDER BY**\
**SQL**\
SELECT * FROM Employees\
ORDER BY Salary DESC;

**Pandas**

In [6]:
df.sort_values(
    "Salary",
    ascending=False
)

     Name  Age  Salary Department
4   Bilal   35  120000         HR
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
1    Sara   25   70000         IT
0     Ali   22   50000         HR

Multiple Columns:\
**SQL**\
ORDER BY Department, Salary DESC

**Pandas**

In [7]:
df.sort_values(
    ["Department","Salary"],
    ascending=[True,False]
)

     Name  Age  Salary Department
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR
0     Ali   22   50000         HR
2   Ahmed   30   90000         IT
1    Sara   25   70000         IT

**4. LIMIT**\
**SQL**\
SELECT * FROM Employees\
LIMIT 3;

**Pandas**

In [8]:
df.head(3)

    Name  Age  Salary Department
0    Ali   22   50000         HR
1   Sara   25   70000         IT
2  Ahmed   30   90000         IT

Last rows:\
**SQL**\
SELECT * FROM Employees\
ORDER BY id DESC\
LIMIT 3;

**Pandas**

In [9]:
df.tail(3)

     Name  Age  Salary Department
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR

**5. DISTINCT**\
**SQL**\
SELECT DISTINCT Department\
FROM Employees

**Pandas**

In [10]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

Count unique:\
**SQL**\
SELECT COUNT(DISTINCT Department)\
FROM Employees;

**Pandas**

In [11]:
df["Department"].nunique()

3

**6. GROUP BY**\
**SQL**\
SELECT Department,\
AVG(Salary)\
FROM Employees\
GROUP BY Department;

**Pandas**

In [3]:
df.groupby("Department")["Salary"].mean()

Department
Finance    80000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

Multiple Aggregations:\
**SQL**\
SELECT Department,\
AVG(Salary),\
MAX(Salary),\
COUNT(*)\
FROM Employees\
GROUP BY Department;

**Pandas**

In [4]:
df.groupby("Department")["Salary"].agg("mean","max","count")

Department
Finance    80000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

**7. HAVING**\
**SQL**\
SELECT Department,\
AVG(Salary)\
FROM Employees\
GROUP BY Department\
HAVING AVG(Salary) > 85000

**Pandas**

In [5]:
grouped = df.groupby("Department")["Salary"].mean()

In [10]:
grouped>85000

Department
Finance    False
HR         False
IT         False
Name: Salary, dtype: bool

In [11]:
grouped[grouped>85000]

Series([], Name: Salary, dtype: float64)

**8. INNER JOIN**\
**SQL**\
SELECT *\
FROM Customers\
INNER JOIN Orders\
ON Customers.CustomerID\
=\
Orders.CustomerID

**Pandas**

In [13]:
customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Ali","Sara","Ahmed"]
})
orders = pd.DataFrame({
    "CustomerID":[1,2,1,4],
    "Product":["Laptop","Phone","Mouse","Keyboard"]
})
pd.merge(
    customers,
    orders,
    on="CustomerID"
)

   CustomerID  Name Product
0           1   Ali  Laptop
1           1   Ali   Mouse
2           2  Sara   Phone

**9. LEFT JOIN**\
**SQL**\
SELECT *\
FROM Customers\
LEFT JOIN Orders\
ON Customers.CustomerID\
=\
Orders.CustomerID

**Pandas**

In [14]:
pd.merge(
    customers,
    orders,
    on="CustomerID",
    how="left"
)

   CustomerID   Name Product
0           1    Ali  Laptop
1           1    Ali   Mouse
2           2   Sara   Phone
3           3  Ahmed     NaN

**10. UNION ALL**\
**SQL**\
SELECT *\
FROM Employess2024\
UNION ALL\
SELECT *\
FROM Employees2025

**Pandas**

In [15]:
df1 = pd.DataFrame({
    "Name":["Ali","Sara"],
    "Age":[23,25]
        })
df2 = pd.DataFrame({
    "Name":["Bilal","Shama"],
    "Age":[26,27]
})
pd.concat(
    [df1,df2],
    ignore_index=True
)

    Name  Age
0    Ali   23
1   Sara   25
2  Bilal   26
3  Shama   27

**11. CASE WHEN**\
**SQL**\
CASE \
WHEN Salary > 100000\
THEN 'Gold'\
ELSE 'Silver\
END

**Pandas**

In [17]:
import numpy as np
df["Tier"] = np.where(
    df["Salary"] > 100000,
    "Gold",
    "Silver"
)

**12. IS NULL**\
**SQL**\
WHERE Salary IS NULL

**Pandas**

In [18]:
df[df["Salary"].isna()]

Empty DataFrame
Columns: [Name, Age, Salary, Department, Tier]
Index: []

**SQL**\
WHERE Salary IS NOT NULL

**Pandas**

In [19]:
df[df["Salary"].notna()]

     Name  Age  Salary Department    Tier
0     Ali   22   50000         HR  Silver
1    Sara   25   70000         IT  Silver
2   Ahmed   30   90000         IT  Silver
3  Ayesha   28   80000    Finance  Silver
4   Bilal   35  120000         HR    Gold

**13. UPDATE**\
**SQL**\
UPDATE Employees\
SET Salary = Salary*1.1

**Pandas**

In [20]:
df["Salary"]*=1.1

In [21]:
df["Salary"]

0     55000.0
1     77000.0
2     99000.0
3     88000.0
4    132000.0
Name: Salary, dtype: float64

Conditional Update:\
**SQL**\
UPDATE Employees\
SET Bonus=10000\
WHERE Salary > 80000

**Pandas**

In [22]:
df.loc[
    df["Salary"]>80000,
    "Bonus"
    ]=10000

In [23]:
df

     Name  Age    Salary Department    Tier    Bonus
0     Ali   22   55000.0         HR  Silver      NaN
1    Sara   25   77000.0         IT  Silver      NaN
2   Ahmed   30   99000.0         IT  Silver  10000.0
3  Ayesha   28   88000.0    Finance  Silver  10000.0
4   Bilal   35  132000.0         HR    Gold  10000.0

**14. DELETE**\
**SQL**\
DELETE\
FROM Employees\
WHERE Salary<60000

**Pandas**

In [29]:
df = df[df["Salary"]>=60000]
df

     Name  Age  Salary Department
1    Sara   25   70000         IT
2   Ahmed   30   90000         IT
3  Ayesha   28   80000    Finance
4   Bilal   35  120000         HR

**15. SQL Query Translation**\
**SQL**\
SELECT Name, Salary\
FROM Employees\
WHERE Department='IT'\
ORDER BY Salary DESC\
LIMIT 2

**Pandas**

In [30]:
df[
    df["Department"]=="IT"
][
    ["Name","Salary"]
].sort_values(
    "Salary",
    ascending=False
).head(2)

    Name  Salary
2  Ahmed   90000
1   Sara   70000