# <center>GroupBy Mastery

**This is arguably the most important Pandas phase.**\
Many people know Pandas.\
Far fewer truly understand groupby().\
Yet, most business questions are basically:\
Take a group of people/items and calculate something about them.\
**Examples:**\
Average salary per department\
Total sales per city\
Maximum spending per customer type\
Average marks per class\
Number of orders per month\
All of these are GroupBy problems.\
**The Core Philosophy**\
Pandas follows: Split --> Apply --> Combine

**Dataset**

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ayesha","Bilal","Usman"],
    "Department":["HR","IT","IT","Finance","HR","Finance"],
    "Age":[22,25,30,28,35,40],
    "Salary":[50000,70000,90000,80000,120000,100000]
})
df

     Name Department  Age  Salary
0     Ali         HR   22   50000
1    Sara         IT   25   70000
2   Ahmed         IT   30   90000
3  Ayesha    Finance   28   80000
4   Bilal         HR   35  120000
5   Usman    Finance   40  100000

**1. Basic GroupBy**\
This one doesn't compute anything.\
It just creates groups.

In [6]:
group = df.groupby("Department")
print(group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000019A516DAFD0>

In [8]:
group.groups

{'Finance': [3, 5], 'HR': [0, 4], 'IT': [1, 2]}

In [9]:
group.groups.keys()

dict_keys(['Finance', 'HR', 'IT'])

In [10]:
list(group.groups.keys())

['Finance', 'HR', 'IT']

This is just preparing the data for the group operations

**2. Mean**

In [11]:
df.groupby("Department")["Salary"].mean()

Department
Finance    90000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

Interpretation : Average Salary per Department

**3. Sum**

In [12]:
df.groupby("Department")["Salary"].sum()

Department
Finance    180000
HR         170000
IT         160000
Name: Salary, dtype: int64

Interpretation : Total Salary per Department

**4. Count**

In [14]:
df.groupby("Department")["Name"].count()

Department
Finance    2
HR         2
IT         2
Name: Name, dtype: int64

Alternative: size()

In [15]:
df.groupby("Department")["Name"].size()

Department
Finance    2
HR         2
IT         2
Name: Name, dtype: int64

**Difference:**\
count() ignores NaN\
size() counts everything

**5. Maximum**

In [17]:
df.groupby("Department")["Salary"].max()

Department
Finance    100000
HR         120000
IT          90000
Name: Salary, dtype: int64

Interpretation : Highest Salary per Department

**6. Minimum**

In [18]:
df.groupby("Department")["Salary"].min()

Department
Finance    80000
HR         50000
IT         70000
Name: Salary, dtype: int64

Interpretation : Lowest Salary per Department

**7. Median**

In [20]:
df.groupby("Department")["Salary"].median()

Department
Finance    90000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

**8. Standard Deviation**

In [21]:
df.groupby("Department")["Salary"].std()

Department
Finance    14142.135624
HR         49497.474683
IT         14142.135624
Name: Salary, dtype: float64

Interpretation:\
Large Std : Employees earn very different salaries.\
Small Std : Employees earn similar salaries.

**9. Multiple Aggregations**\
Real analysts rarely compute only one thing.

In [23]:
df.groupby("Department")["Salary"].agg(
    ["sum","mean","median","max","min","count","std"]
)

               sum     mean   median     max    min  count           std
Department
Finance     180000  90000.0  90000.0  100000  80000      2  14142.135624
HR          170000  85000.0  85000.0  120000  50000      2  49497.474683
IT          160000  80000.0  80000.0   90000  70000      2  14142.135624

**10. Named Aggregations**\
Professionals often rename outputs.

In [24]:
df.groupby("Department").agg(
    AverageSalary = ("Salary","mean"),
    HighestSalary = ("Salary","max"),
    LowestSalary = ("Salary","min"),
    EmployeeCount = ("Name","size")
)

            AverageSalary  HighestSalary  LowestSalary  EmployeeCount
Department
Finance           90000.0         100000         80000              2
HR                85000.0         120000         50000              2
IT                80000.0          90000         70000              2

**11. Grouping By Multiple Columns**

In [10]:
Gender = pd.Series(["Male","Female","Male","Female","Male","Male"])
df["Gender"]=Gender

In [11]:
df

     Name Department  Age  Salary  Gender
0     Ali         HR   22   50000    Male
1    Sara         IT   25   70000  Female
2   Ahmed         IT   30   90000    Male
3  Ayesha    Finance   28   80000  Female
4   Bilal         HR   35  120000    Male
5   Usman    Finance   40  100000    Male

In [12]:
df.groupby(
    ["Department","Gender"]
)["Salary"].mean()

Department  Gender
Finance     Female     80000.0
            Male      100000.0
HR          Male       85000.0
IT          Female     70000.0
            Male       90000.0
Name: Salary, dtype: float64

This is called a Multi Index

**12. as_index = False**

In [14]:
df.groupby(
    "Department",
    as_index=False
)["Salary"].mean()

  Department   Salary
0    Finance  90000.0
1         HR  85000.0
2         IT  80000.0

Notice that with as_index = False, the department becomes a normal column rather than the index itself. It is useful before exporting to CSV.

**13. Sorting Group Results**

In [15]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
Finance    90000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

**14. Business Questions**

Average Salary by Department

In [16]:
df.groupby("Department")["Salary"].mean()

Department
Finance    90000.0
HR         85000.0
IT         80000.0
Name: Salary, dtype: float64

Number of Employees by Gender

In [17]:
df.groupby("Gender")["Name"].count()

Gender
Female    2
Male      4
Name: Name, dtype: int64

Number of Employees per Department

In [19]:
df.groupby("Department")["Name"].count()

Department
Finance    2
HR         2
IT         2
Name: Name, dtype: int64