# <center>Advanced String Processing

If Window Functions are the king of numerical analytics, String Processing is the king of data cleaning.\
But Most of the real-world datasets are not messy because of numbers but because of **text**\
Before you build a model, you'll spend a lot of time cleaning these values

**Dataset**

In [7]:
import pandas as pd
df = pd.DataFrame({
    "Name":[
        " ali ",
        "SARA",
        "ahMed",
        " John Doe "
    ],
    "Email":[
        "ali@gmail.com",
        "SARA@Yahoo.com",
        "ahmed123@gmail.com",
        "john@company.org"
    ],
    "Department":[
        "IT Department",
        "HR Department",
        "Finance Department",
        "IT Department"
    ],
    "Code":[
        "EMP-001",
        "EMP-002",
        "EMP-003",
        "EMP-004"
    ]
})
df

         Name               Email          Department     Code
0        ali        ali@gmail.com       IT Department  EMP-001
1        SARA      SARA@Yahoo.com       HR Department  EMP-002
2       ahMed  ahmed123@gmail.com  Finance Department  EMP-003
3   John Doe     john@company.org       IT Department  EMP-004

**Important** : Strings in Pandas are manipulated through the **.str** accessor

**1. lower()**\
converts everything to lowercase

In [2]:
df["Name"].str.lower()

0          ali
1          sara
2         ahmed
3     john doe
Name: Name, dtype: object

**2. upper()**\
converts everything to uppercase

In [3]:
df["Name"].str.upper()

0          ALI
1          SARA
2         AHMED
3     JOHN DOE
Name: Name, dtype: object

**3. title()**\
converts everything to title case

In [4]:
df["Name"].str.title()

0          Ali
1          Sara
2         Ahmed
3     John Doe
Name: Name, dtype: object

**4. strip()**\
Removes leading and trailing spaces

In [5]:
df["Name"].str.strip()

0         ali
1        SARA
2       ahMed
3    John Doe
Name: Name, dtype: object

There are also:\
lstrip() --> Removes leading spaces\
rstrip() --> Removes trailig spaces

**5. replace()**\
Replace text

In [8]:
df["Department"].str.replace(
    "Department",
    ""
)

0         IT
1         HR
2    Finance
3         IT
Name: Department, dtype: object

Regex replacement:

In [9]:
df["Department"].str.replace(
    r"\d",
    "",
    regex=True
)

0         IT Department
1         HR Department
2    Finance Department
3         IT Department
Name: Department, dtype: object

It removes every digit

**6. contains()**\
Find text

In [10]:
df["Email"].str.contains(
    "gmail"
)

0     True
1    False
2     True
3    False
Name: Email, dtype: bool

Case insensitive check:

In [11]:
df["Email"].str.contains(
    "gmail",
    case=False
)

0     True
1    False
2     True
3    False
Name: Email, dtype: bool

Regex:\
Eg: Contains numbers?

In [12]:
df["Email"].str.contains(
    r"\d"
)

0    False
1    False
2     True
3    False
Name: Email, dtype: bool

**7. startswith() and endswith()**

In [13]:
df["Code"].str.startswith("EMP")

0    True
1    True
2    True
3    True
Name: Code, dtype: bool

In [14]:
df["Email"].str.endswith(".com")

0     True
1     True
2     True
3    False
Name: Email, dtype: bool

**8. split()**\
breaks a string

In [15]:
df["Name"].str.split()

0          [ali]
1         [SARA]
2        [ahMed]
3    [John, Doe]
Name: Name, dtype: object

Split and Exapnd into columns:

In [16]:
df["Name"].str.split(
    expand=True
)

       0     1
0    ali  None
1   SARA  None
2  ahMed  None
3   John   Doe

**9. cat()**\
Concatenate strings

In [17]:
df["Name"].str.cat(
    df["Department"],
    sep = '-'
)

0          ali -IT Department
1          SARA-HR Department
2    ahMed-Finance Department
3     John Doe -IT Department
Name: Name, dtype: object

**10. len()**

In [19]:
df["Email"].str.len()

0    13
1    14
2    18
3    16
Name: Email, dtype: int64

**11. slice()**

In [21]:
df["Code"].str.slice(2)

0    P-001
1    P-002
2    P-003
3    P-004
Name: Code, dtype: object

Equivalent to: .str[4: ]

**12. extract()**\
Extract digits:

In [22]:
df["Code"].str.extract(
    r"(\d+)"
)

     0
0  001
1  002
2  003
3  004

Extract letters:

In [23]:
df["Code"].str.extract(
    r"([A-Z]+)"
)

     0
0  EMP
1  EMP
2  EMP
3  EMP

Extract Email Username:

In [24]:
df["Email"].str.extract(
    r"(^.*)@"
)

          0
0       ali
1      SARA
2  ahmed123
3      john

**13. extractall()**

In [25]:
s = pd.Series(["A12B45C89"])

s.str.extractall(
    r"(\d+)"
)

          0
  match
0 0      12
  1      45
  2      89

Unlike extract(), it finds every single match

**14. findall()**

In [27]:
s.str.findall(
    r"(\d+)"
)

0    [12, 45, 89]
dtype: object

**15. match()**\
Check whether the beginning matches

In [28]:
df["Code"].str.match(
    r"EMP"
)

0    True
1    True
2    True
3    True
Name: Code, dtype: bool

**fullmatch():** Whole String match

In [29]:
df["Code"].str.fullmatch(
    r"EMP-\d{3}"
)

0    True
1    True
2    True
3    True
Name: Code, dtype: bool