# <center>Performance Optimization and Memory Efficiency

This phase teaches you how professionals work with datasets containing millions of rows.\
**The goal is:**\
Write Pandas code that is:\
✔ Fast\
✔ Memory-efficient\
✔ Production-ready\
✔ Scalable\
Most beginners only care about making code work.\
**Professionals care about:**\
How much RAM?\
How much time?\
Will this work on 50 million rows?

**Dataset**

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "ID" : np.arange(100000),
    "Department" : np.random.choice(["HR","IT","Finance"],100000),
    "Salary" : np.random.randint(40000,150000,100000)
})
df

          ID Department  Salary
0          0         HR   46856
1          1    Finance  119044
2          2         HR  114548
3          3    Finance  108115
4          4         HR   87324
...      ...        ...     ...
99995  99995         HR   90796
99996  99996         IT   56609
99997  99997         IT   66348
99998  99998         IT  139619
99999  99999    Finance  137555

[100000 rows x 3 columns]

**1. Measuring Memory Usage**\
First rule : You cannot optimize what you don't measure.\
**memory_usage():**

In [2]:
df.memory_usage()

Index            132
ID            800000
Department    800000
Salary        400000
dtype: int64

**Total Memory:**

In [3]:
df.memory_usage().sum()

np.int64(2000132)

**Human Friendly in MBs**

In [4]:
df.memory_usage().sum() / 1024**2

np.float64(1.9074745178222656)

**2. Deep Memory Inspection**\
Object columns are tricky.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   ID          100000 non-null  int64
 1   Department  100000 non-null  object
 2   Salary      100000 non-null  int32
dtypes: int32(1), int64(1), object(1)
memory usage: 1.9+ MB

In [8]:
df.info(
    memory_usage = "deep"
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   ID          100000 non-null  int64
 1   Department  100000 non-null  object
 2   Salary      100000 non-null  int32
dtypes: int32(1), int64(1), object(1)
memory usage: 6.2 MB

In [9]:
df["Department"].info(
    memory_usage = "deep"
)

<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Department
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 5.0 MB

**Why?**:\
Because object dtype stores pointers to Python objects.\
The actual strings are elsewhere in memory.

**3. astype()**\
One of the easiest optimizations.

**Common Optimizations**

a. Large Integers\
int64 --> int32

b. Small Integers\
int64 --> int16

c. Floating points\
float64-->float32

**Professional Rule:** Use the smallest datatype that safely holds your values

**4. Category Dtype**\
One of the biggest memory optimizations in Pandas

In [13]:
df["Department"] = df[
    "Department"
].astype(
    "category"
)

In [14]:
df["Department"].dtype

CategoricalDtype(categories=['Finance', 'HR', 'IT'], ordered=False, categories_dtype=object)

In [16]:
df.memory_usage()

Index            132
ID            800000
Department    100132
Salary        400000
dtype: int64

**Before:**\
HR HR HR IT IT Finance\
Each string stored separately.

**After:**\
Categories:\
0 → Finance\
1 → HR\
2 → IT\

**Internally:**\
1 1 1 2 2 0\
Huge memory savings.

**5. Vectorization**

Bad:

In [20]:
for i in range(len(df)):

    df.loc[i,"Bonus"] = (
        df.loc[i,"Salary"]
        * 0.1
    )

This is slow.

Good:

In [22]:
df["Bonus"] = (
    df["Salary"]
    * 0.1
)

This is very fast

**6. iterrows() vs itertuples()**\
Sometimes loops are unavoidable\
**iterrows()**

In [23]:
for index,row in df.iterrows():

    print(
        row["Salary"]
    )

46856
119044
114548
108115
87324
148262
138500
71950
42116
45023
144020
123922
116680
63546
120549
129591
99670
149836
97924
140904
63981
135883
79085
91048
47990
142205
137420
105078
83488
104511
43388
61489
75993
120404
92930
65338
69134
42796
80330
143428
72546
141078
145627
117399
102641
139709
131581
59000
68673
102822
67417
52988
57244
136444
60443
135821
63228
48060
111498
81242
81094
143763
43290
141745
104171
42418
95443
119510
67820
46740
78379
121002
137111
131555
142889
142714
90053
96798
125792
57089
140762
123987
50605
72391
109047
96433
42338
132914
104438
81787
65602
134174
148444
79085
98995
148479
147812
104710
64255
120269
133899
65046
132200
53478
78278
131219
83642
56621
104808
140329
100015
144311
112346
81582
84701
143091
84077
49657
87069
64019
48846
141226
75497
106940
130863
119280
48111
139511
63752
86607
141885
128596
143836
55387
46455
68524
129974
109169
65439
129383
43100
40027
49968
108963
139447
93927
120882
67837
98045
57711
91813
142028
133109
128053
72778
118333
131535
92642
149246
126952
94820
81714
86007
109701
56906
124449
53181
53762
69674
61630
84637
64385
130635
98859
104964
119259
137402
146171
141849
54993
108346
109937
119668
90630
45623
97400
103126
89811
49721
112138
139304
61297
46574
75910
138097
146049
105405
40580
132922
81771
138724
145540
68601
43845
145329
43258
81789
64746
40179
51130
144000
91576
111595
84627
43525
46228
103593
84540
145721
137087
76988
107433
92931
54109
84909
43237
112995
149412
42336
57805
106593
110313
41220
58745
129412
110240
108364
63315
132564
58231
62426
54153
112980
78101
75019
130514
144716
64179
58188
63572
104431
103507
124530
103726
90340
146057
66275
45758
82367
98833
65437
44043
112565
41539
131826
114821
53915
129448
138065
100747
57648
46543
84536
77991
98321
93870
101443
75178
146782
52785
145987
88971
103130
113740
41217
98344
107924
127205
76091
114607
65888
40517
122815
56068
49265
53381
83251
99015
76657
85752
108173
50653
110733
67314
91826
43848
110279
91689
120079
63396
89239
99576
87241
45960
56823
147928
98152
112563
64084
75540
95514
53582
94436
109025
144405
113375
84499
105523
79030
47065
62750
116135
130562
65489
60888
144890
49451
75848
91832
123302
145557
44366
40687
68816
120398
145883
82661
61224
142511
99049
116987
96360
42742
135253
104157
117385
49711
143917
56659
127308
130348
54461
126052
48421
62956
95840
83200
83053
85258
94549
114727
149077
142402
115901
84168
127349
58898
105054
106213
57274
73146
98764
142833
76122
125324
109600
117393
105646
41967
135602
92972
101529
70764
50745
70099
111703
63310
60423
61594
44315
59317
44100
91786
65473
146643
83815
46712
145656
54563
99224
51295
70103
92073
117629
115780
111955
50286
83115
82019
149803
105962
51406
120713
147738
44465
63595
82217
47073
69969
102283
108492
118060
105623
111750
83518
137966
96011
86412
113024
114113
117775
61629
126448
74632
134385
74591
133774
146117
48792
45008
106810
93000
64576
112049
112998
54157
97320
44473
141867
134388
83068
53116
42606
88927
64304
50104
71570
81325
76503
147081
105751
128900
92249
76246
100619
73962
149490
77616
73453
56660
91317
72487
106453
136193
112515
112145
103038
149482
84982
41151
88644
61006
131614
64939
60496
55906
146775
63793
62249
85101
87953
104468
56801
87577
56954
107823
52524
75059
135815
75304
139459
42965
119125
87935
55924
128174
49284
124167
52687
129025
96795
103907
89374
79567
89215
53376
40148
57415
115808
130875
42284
69503
54522
85442
67466
121895
68623
48145
122858
118872
52826
57015
119207
65459
79271
107727
41920
97883
99383
138656
145436
147629
93967
51025
65331
60840
107446
111838
141670
50525
65184
69395
97656
134532
58736
128628
72953
70120
106579
143623
54821
71995
96737
62807
51621
103005
108872
45281
132798
102374
108768
140044
141493
138352
137109
45087
132135
135918
61387
49441
111341
64121
118908
54048
144852
87495
62914
81132
135204
148673
55009
54045
63308
123014
83853
106685
100949
143871
132907
67651
132059
126693
119287
131836
53212
102783
89322
48630
116576
90275
118710
148843
44302
104131
84764
141543
136675
122148
120963
110172
76608
60333
100871
125254
120711
148350
132312
130255
59232
119995
45729
56082
65366
135433
95005
109525
132253
110021
91287
118842
89008
113357
130057
51711
95022
100888
143574
110762
52364
118827
82722
67351
131836
124687
96899
127517
130656
94557
59297
59040
53554
89939
141462
124783
63287
73657
102763
84786
91010
59746
99860
98748
92940
139110
85942
69995
79183
138368
148650
122254
125681
114462
57176
137232
58208
43499
111826
75758
143824
41167
69596
101340
115076
78536
73819
113946
73501
68899
123383
144569
126087
83672
131949
52451
106434
74795
125706
76771
124676
91636
53141
113612
71611
111387
90486
116220
86323
67650
99918
121884
75228
102149
68957
81353
66619
109620
114785
53184
134513
109876
87642
144776
93032
43527
143419
80565
76202
84957
82488
75051
119000
90244
110666
115681
59719
128616
80493
102745
57214
41448
148374
137780
126273
87179
108465
57116
110215
118763
67856
116162
70796
118294
65398
103274
107340
71344
97162
92672
54151
117947
149025
107964
115305
43429
105119
54859
76135
110924
54396
80609
43534
99777
58005
82815
109880
94476
101923
113997
57646
62007
45210
133775
122515
120876
58696
134074
65287
65573
120114
126531
52008
93934
107374
92647
127046
123382
94710
97738
50566
61826
96149
83127
139937
42989
121218
65517
84926
44553
70840
149198
145959
41821
84953
76585
116026
45287
138875
81767
67424
53139
125675
122403
125273
74910
70257
94248
97466
65060
84279
110392
54089
74352
81479
76676
104259
56961
90001
57565
128332
149282
128940
100217
96060
97895
79641
47164
108110
78038
75896
97191
55724
111014
81942
68444
142538
93074
84770
136166
81482
106777
84906
122748
127010
60478
141367
63241
137883
91425
120313
72959
104818
85183
135589
137251
63062
111242
63812
106620
50972
74463
64742
93483
126046
85669
122211
80918
103938
58254
103794
69442
78255
113284
144807
105755
102744
123420
66999
88905
103574
117106
82684
55782
40247
101397
137373
145303
70013
92052
55187
147852
104576
72715
90878
122823
56286
128643
92682
80748
64762
93087
56266
136944
119141
125001
59270
60313
116818
133230
107710
93503
141990
107356
40786
104003
44189
80275
144423
108855
118623
129045
50524
80907
57090
47229
136666
70430
147332
101148
76220
109313
127428
52374
45657
51686
52618
119802
83469
75643
50502
121540
117655
99736
84583
141422
135438
89696
69005
41511
127921
124368
40538
109833
73166
78083
118432
41363
101886
54800
42629
60624
67434
94767
97091
109108
51495
54431
62103
68635
86937
148729
43562
98045
124547
88853
49923
124970
102702
119108
86370
52975
56271
87832
74035
43967
40051
80513
120521
47997
138593
93568
46225
44934
136477
57731
129170
77597
141539
66952
131825
89898
77389
139546
147569
81154
93578
144807
85839
144193
86692
84644
104216
68515
40394
57184
73338
119318
40288
91784
41312
86065
67478
59592
75199
115443
135735
148714
47894
128475
62786
89597
46616
76034
132176
96166
52078
109988
105848
55439
54961
131678
127162
45289
65903
81148
93811
113511
88560
52692
141851
127606
63982
139314
130377
105976
68342
111664
130265
68439
117890
63247
111474
97694
64308
143355
136952
61322
81269
146781
118200
65260
72058
66116
120879
48211
42200
119435
95059
46567
102904
100934
57801
42779
100587
55248
108084
55111
106565
96102
98591
49598
149350
91245
106847
127513
94656
110488
77935
49451
84755
45182
96215
60081
49033
66441
120510
106471
116063
138273
142322
147500
66057
139567
43891
116428
132859
89186
48790
108765
100705
52521
149630
125638
71499
47975
112130
44963
96411
103551
129395
109501
75131
104399
44613
57818
88279
54047
71949
143810
87094
60914
126414
127805
94695
48642
88261
142776
42041
95428
123437
67283
74511
51769
127953
69686
88000
85155
121559
97815
51439
117408
44963
140535
49753
127345
138665
136302
102726
80014
59525
48261
102599
112209
74547
127445
84387
136213
99356
109104
111747
137548
95690
66209
41358
62994
138804
99963
104773
123831
53316
102154
50719
61164
143277
116379
88186
49193
148750
143836
116547
94727
117248
104335
143587
127665
71007
63920
78136
58594
93073
68649
67375
88646
119551
103126
95843
43780
86520
72338
125885
149321
89049
85809
71232
124663
121609
82120
82364
61127
138793
102843
101621
112731
42482
91986
126382
149649
113349
149101
85006
40460
81260
125941
140778
112222
117298
83564
96309
48833
116464
120563
98986
114531
89657
114995
79222
132714
131579
47196
107292
68373
119857
128282
101589
82949
77862
46586
106675
110672
63798
59964
108561
95749
44850
94029
142225
55135
107983
133732
95455
58458
62171
149757
82601
59898
76570
73590
58098
144046
148084
83710
129307
134259
96595
84054
62996
130779
129592
104676
114984
111406
141616
106319
142941
42299
65846
55801
87143
77450
137884
65297
90279
124245
50626
117291
130906
145823
60653
99269
94661
67112
114659
90737
47405
85260
61248
64283
113245
139720
149132
56378
128472
90229
126445
86906
48086
118823
54046
73205
109005
73212
93308
50813
52721
104614
91730
103824
129078
130701
144843
75006
60746
115516
65705
40884
71974
50891
141365
121775
59325
81576
111532
53098
110470
111450
41697
76950
119090
49688
117670
105070
98036
56232
102726
146214
138264
75620
148030
143763
92325
141609
48764
141377
102736
138744
91614
140256
93716
77558
143217
62055
55972
101429
62617
51648
44745
75990
135506
98983
133816
43885
120557
104887
52218
45930
48321
112637
89606
47338
96123
119695
142941
103400
47600
115837
46689
117409
78880
86029
127489
93452
116757
135262
104579
73586
56912
69779
98000
142882
44202
107096
58982
119184
64751
89314
50557
67457
51378
88371
112214
103302
59224
87737
79276
114067
53350
43312
103158
67379
97244
126005
84903
87592
133460
82916
111140
141129
55448
87021
71727
144566
143468
50380
143449
54916
70397
107357
54999
128404
46350
65480
52726
148820
134990
52198
69083
69245
148099
50180
46874
138909
94183
104145
49568
102205
86740
117510
88974
100510
141433
110007
48418
95721
147119
100886
75660
85978
66429
92915
141600
103423
58468
80793
51953
73348
126213
147589
146061
45000
42820
119629
76073
77049
124980
114596
114524
139853
71707
122084
79158
46236
137803
40393
116376
71583
59079
109558
62323
140821
100053
119668
120616
46297
119494
84879
60169
108488
111576
138187
67546
78742
126929
88127
70728
82501
79657
78141
140918
91430
61109
101398
88952
42950
58932
92838
55920
106618
69197
126626
88935
94819
83249
65326
96630
73169
69570
103538
115893
76218
61974
117031
81948
54395
55498
104548
142097
114482
116021
70896
113076
113715
69890
140947
149214
113575
51371
76401
93578
88374
80336
80967
146508
81456
80718
99736
117760
78338
59133
89068
72603
50440
97272
138732
138532
110037
72994
141075
91577
120281
88629
100606
76445
40375
75497
86515
75871
40890
104466
80691
51714
90688
122177
122232
117463
103945
56156
76280
67089
52200
61144
42409
97200
73939
54423
72455
87265
62966
117532
43652
99149
68785
144241
80964
146999
78100
143585
103743
100448
130771
103929
52477
59474
82529
73863
51889
82658
65881
136965
146789
89163
76307
115795
50927
71193
135393
90781
40880
123815
80314
77831
76062
105213
111815
146791
92372
124117
144901
106339
91910
105117
88733
70299
51946
105733
42578
95321
75711
108121
57496
128632
94123
122714
42632
145038
92780
105670
99074
66530
147568
65432
120086
66134
119279
72755
117809
107535
85666
137820
58153
45333
100064
52117
133241
113173
115156
131474
99492
134418
101208
115118
147619
48502
72302
51716
91584
55749
52787
129912
79205
64822
59385
100342
75253
146675
51221
102869
142722
103147
128232
93503
71020
54547
42773
70581
59159
134118
137696
115614
133794
77328
72670
63422
68024
69681
149906
123099
57535
46168
69392
67430
90608
59485
52808
129463
80297
123286
48152
68759
77591
94465
73431
114505
86296
138061
50288
107793
112062
73642
62361
42854
94415
141662
147302
106434
86862
143998
97906
114716
78887
101099
57597
102491
116098
112637
71607
129744
105288
136949
56819
137216
45631
110389
90281
139958
47271
54714
57926
93936
63785
112131
110045
57592
105249
84269
63063
91529
104332
143168
118751
96362
104915
111298
99785
120862
149873
110133
105988
84544
68056
122311
89404
101346
54960
80538
43643
142613
101880
90573
55058
49741
115345
41739
133039
88199
144997
126212
72876
69979
92025
52720
92242
146477
115418
72783
60572
148983
121627
113139
78380
64429
141350
61222
115211
67466
61594
116884
141367
115297
128823
64829
102590
83780
65907
51481
104674
92070
87696
115994
104902
76361
147108
121052
101040
113485
42622
121342
76465
53799
112735
59343
145549
64640
141656
140815
140391
97998
132827
79765
69985
95457
56146
46319
42316
77951
51911
62705
117192
74115
149167
114342
81780
85501
94900
45254
149160
132160
119622
100587
40280
79665
88297
119967
94071
99126
106227
114166
48481
83592
84629
49715
123460
121032
67421
104667
90243
78356
138278
105147
114092
54599
129785
61484
133112
82333
118975
122385
123015
118471
55713
90707
85957
99361
141979
89279
57660
118794
40345
53179
84706
100721
109325
131463
123385
48457
70452
142333
148173
67433
117326
84255
133420
87589
54547
115972
73313
72612
124113
84850
63378
81696
45379
60514
108477
81181
106430
125677
57939
44298
83142
95615
120927
99322
92433
148281
111852
84024
78662
75894
73809
145548
84943
136885
133986
52136
69199
85055
120068
52581
120808
72315
75657
139193
131512
146875
116731
70651
49511
96053
124308
136967
123723
122077
90736
124866
90370
148268
71091
143739
105618
118641
94618
139914
123496
125758
145577
50290
62887
146040
129231
145642
84563
96549
40973
91290
139770
65198
111061
88805
121407
112181
148785
80506
131116
137298
75250
76712
131526
137117
50119
133147
68824
128379
93957
81141
46560
87960
128212
120669
59750
121559
70078
116333
45955
119176
73360
138199
116238
107081
98612
138961
67633
79661
62306
54207
65304
134866
55871
116797
126135
106808
117817
102651
66351
53782
113982
125382
149117
94656
148991
124753
142474
144422
78993
43800
121483
59787
88190
121711
123741
121196
91099
60269
49611
74308
59182
66353
86197
137780
49583
100348
65393
91373
132372
61058
120867
140068
91816
71665
134646
99267
54671
80530
98856
112772
40741
58570
96940
69172
146008
112262
137761
57206
112714
58909
92762
129341
146272
105240
103650
132540
127353
67297
128035
94227
114426
125990
122188
70100
79170
114347
105086
55252
52822
58329
141339
121229
149809
135714
89874
125549
42147
100282
100356
49903
66181
128116
112302
65478
145564
86128
144095
50817
87506
85490
123564
143310
125575
116703
108731
92736
100854
87612
72005
76620
132696
103049
78318
41437
138568
80639
43146
57369
82366
92647
97281
96969
78393
105451
132062
87804
42112
128751
52163
100645
121444
83194
146869
112966
99265
67431
62940
130489
85881
120372
124342
130859
87960
79515
78975
141209
145416
72751
97411
55810
132178
43119
112902
124550
50033
98302
112631
56208
69465
69139
106087
112128
89931
89746
87172
144965
121838
46964
83336
87112
144105
56962
131586
59832
76217
106680
125520
55275
121354
71399
114124
88551
52972
67946
76958
75535
91886
98159
78849
82975
92336
141002
55609
117354
99502
85930
60559
68040
139682
52630
65549
147450
92497
145454
71848
51322
113972
140032
109064
126752
94233
104496
132150
99096
53216
132936
46861
47138
105384
68513
67416
41642
144939
45517
79907
102071
143896
103996
92790
145180
55248
91510
144479
122795
59886
41881
55277
113841
56975
56039
63283
143871
129835
132527
91267
106504
95695
83026
129260
54078
124247
140610
131998
57188
142495
71982
80832
127262
130421
118424
84976
62074
70684
139605
146143
132813
144128
91228
75119
113311
85403
94777
45945
52740
85417
72547
143109
145746
101497
135206
143728
98515
94139
61127
46202
67703
143419
63342
51065
106915
79037
124809
107769
139092
130382
69817
54522
117406
102877
97743
46823
46747
43934
67947
119624
48040
84351
129427
116829
88014
69130
75153
76097
135748
133119
128759
107226
51735
107237
128382
133128
145528
87592
53012
58025
72980
47476
98980
126718
100960
67849
106615
90027
59155
102492
111986
43256
40275
106766
94141
51362
82348
51615
94856
40680
88158
71636
68271
131019
85980
93409
97669
101289
77327
129504
45165
145859
146280
124792
95843
133092
126617
90471
46300
143549
69192
47959
61765
74824
42888
71169
115421
130358
125209
120857
73126
44406
55963
61294
44904
75474
109522
57820
79184
125577
52852
56975
69240
99330
92264
75850
118435
73042
110402
59158
69773
102354
58752
80599
148327
65070
89814
77715
81649
45254
97231
69744
62939
41971
125298
134661
101355
90283
47358
141022
115884
134011
130006
88550
103812
82515
52235
56411
127208
43264
138155
129396
135894
76963
81757
140241
114561
91123
93896
108948
97600
93932
58299
113754
104184
48223
44349
110588
79667
146160
131368
61205
73925
92355
44262
136381
109065
77110
82579
136928
77852
109970
108418
110751
91156
53957
48823
82700
135934
82645
136709
41630
141209
146497
86500
92190
77414
120199
125353
143771
130377
116302
89804
100033
111185
136184
145942
146526
147928
80325
87191
71666
137361
106114
103258
73673
56335
135422
77913
129565
123563
117971
87488
130624
86106
70940
54944
84156
54699
108559
103180
93430
137581
58924
71911
114678
71389
105512
96293
87671
40250
96774
141011
71989
138476
71324
147284
149841
61776
71109
103748
140765
69472
126477
116467
71164
70880
110273
122174
102836
126013
146895
148149
46379
102253
147552
58405
129445
72330
126703
56259
44463
120846
96566
45782
119907
119984
112327
61931
103482
134278
119162
74224
95777
49885
80716
64056
73542
67133
121649
97571
40548
58556
125894
123457
94545
68781
128961
55628
49393
74803
41288
120577
62379
65979
45519
82949
124155
112380
120324
50829
122525
59706
71859
80157
129196
144354
136838
142709
119344
109955
127149
72463
108827
116919
110988
120082
63631
142466
46899
85811
113339
48930
75621
105643
61800
42936
78005
61560
72199
77482
109881
134551
137371
84194
148429
50658
117556
129302
65225
45850
55707
133544
75562
40345
119194
62834
142051
115331
149231
59664
40652
126816
74584
110895
88870
87212
142565
123283
91440
48969
118623
91947
101637
73862
84990
139320
81246
91984
53613
141733
147005
77676
48371
123641
120614
114133
143609
108838
115891
72014
80848
137538
60286
93240
77838
97609
41781
65191
140861
136536
78543
61729
50414
99836
93449
131370
69332
137289
120248
149256
62195
121818
98461
78887
133798
40947
65272
93995
109163
89015
44982
81832
105696
52097
114710
59248
104796
106866
101078
107807
70106
87360
134791
100966
70299
138346
129039
143131
143391
55706
79748
43549
95233
64643
130432
75409
114800
58493
112251
82477
110566
146414
41071
56668
47179
133284
134362
72015
94550
68141
106489
139873
68650
68424
106957
148200
87019
47776
118512
46947
59656
77012
128516
45295
40411
86723
48241
114792
110460
65212
49963
40324
138236
77641
83109
142878
61337
58893
144657
104800
118170
49193
100465
70357
127183
143114
123662
94544
41924
142847
144433
76840
148727
124759
106924
76041
139949
140281
122690
44181
67240
78001
85758
62445
53382
74697
60233
46350
118143
49577
133490
58748
70833
80907
141213
52742
52645
53901
58214
78601
61133
66627
88318
65886
129764
56807
102861
47036
103794
56447
124592
111074
51138
82735
95461
114011
111847
129068
81200
126953
74428
100045
133876
134958
57469
99219
73660
142708
45253
82747
135016
88561
74146
121456
63604
104828
72533
72617
114667
134910
68626
94516
42358
97532
136415
125308
123240
109735
145998
139690
102342
102119
60387
45168
125135
141854
139799
116088
42969
84076
55575
88112
56429
129921
103357
99155
137622
53983
59103
93526
120274
86187
94430
102463
109741
88023
52111
109275
120377
126847
48134
93266
71683
63356
54456
115402
145578
100030
53662
61609
46530
136226
147479
76641
79952
139141
94471
56027
94599
133207
66627
128538
89958
108742
50482
62871
103003
95677
98968
60122
112778
62367
114919
144381
57720
79945
79382
147083
122650
63643
67568
131463
48558
107685
71853
142272
148844
133253
56112
62252
125668
99431
83592
41890
130362
81251
144438
146277
73172
109807
103449
66906
141293
129122
55744
138280
98507
103780
49287
51145
112380
95912
92874
51470
105215
91949
66184
126062
71818
63537
85461
105480
42499
144761
120358
129780
62673
137364
131167
70675
113704
130260
49506
109442
132109

Very slow\
Because each row converts into series

**itertuples()**

In [24]:
for row in df.itertuples():

    print(
        row.Salary
    )

46856
119044
114548
108115
87324
148262
138500
71950
42116
45023
144020
123922
116680
63546
120549
129591
99670
149836
97924
140904
63981
135883
79085
91048
47990
142205
137420
105078
83488
104511
43388
61489
75993
120404
92930
65338
69134
42796
80330
143428
72546
141078
145627
117399
102641
139709
131581
59000
68673
102822
67417
52988
57244
136444
60443
135821
63228
48060
111498
81242
81094
143763
43290
141745
104171
42418
95443
119510
67820
46740
78379
121002
137111
131555
142889
142714
90053
96798
125792
57089
140762
123987
50605
72391
109047
96433
42338
132914
104438
81787
65602
134174
148444
79085
98995
148479
147812
104710
64255
120269
133899
65046
132200
53478
78278
131219
83642
56621
104808
140329
100015
144311
112346
81582
84701
143091
84077
49657
87069
64019
48846
141226
75497
106940
130863
119280
48111
139511
63752
86607
141885
128596
143836
55387
46455
68524
129974
109169
65439
129383
43100
40027
49968
108963
139447
93927
120882
67837
98045
57711
91813
142028
133109
128053
72778
118333
131535
92642
149246
126952
94820
81714
86007
109701
56906
124449
53181
53762
69674
61630
84637
64385
130635
98859
104964
119259
137402
146171
141849
54993
108346
109937
119668
90630
45623
97400
103126
89811
49721
112138
139304
61297
46574
75910
138097
146049
105405
40580
132922
81771
138724
145540
68601
43845
145329
43258
81789
64746
40179
51130
144000
91576
111595
84627
43525
46228
103593
84540
145721
137087
76988
107433
92931
54109
84909
43237
112995
149412
42336
57805
106593
110313
41220
58745
129412
110240
108364
63315
132564
58231
62426
54153
112980
78101
75019
130514
144716
64179
58188
63572
104431
103507
124530
103726
90340
146057
66275
45758
82367
98833
65437
44043
112565
41539
131826
114821
53915
129448
138065
100747
57648
46543
84536
77991
98321
93870
101443
75178
146782
52785
145987
88971
103130
113740
41217
98344
107924
127205
76091
114607
65888
40517
122815
56068
49265
53381
83251
99015
76657
85752
108173
50653
110733
67314
91826
43848
110279
91689
120079
63396
89239
99576
87241
45960
56823
147928
98152
112563
64084
75540
95514
53582
94436
109025
144405
113375
84499
105523
79030
47065
62750
116135
130562
65489
60888
144890
49451
75848
91832
123302
145557
44366
40687
68816
120398
145883
82661
61224
142511
99049
116987
96360
42742
135253
104157
117385
49711
143917
56659
127308
130348
54461
126052
48421
62956
95840
83200
83053
85258
94549
114727
149077
142402
115901
84168
127349
58898
105054
106213
57274
73146
98764
142833
76122
125324
109600
117393
105646
41967
135602
92972
101529
70764
50745
70099
111703
63310
60423
61594
44315
59317
44100
91786
65473
146643
83815
46712
145656
54563
99224
51295
70103
92073
117629
115780
111955
50286
83115
82019
149803
105962
51406
120713
147738
44465
63595
82217
47073
69969
102283
108492
118060
105623
111750
83518
137966
96011
86412
113024
114113
117775
61629
126448
74632
134385
74591
133774
146117
48792
45008
106810
93000
64576
112049
112998
54157
97320
44473
141867
134388
83068
53116
42606
88927
64304
50104
71570
81325
76503
147081
105751
128900
92249
76246
100619
73962
149490
77616
73453
56660
91317
72487
106453
136193
112515
112145
103038
149482
84982
41151
88644
61006
131614
64939
60496
55906
146775
63793
62249
85101
87953
104468
56801
87577
56954
107823
52524
75059
135815
75304
139459
42965
119125
87935
55924
128174
49284
124167
52687
129025
96795
103907
89374
79567
89215
53376
40148
57415
115808
130875
42284
69503
54522
85442
67466
121895
68623
48145
122858
118872
52826
57015
119207
65459
79271
107727
41920
97883
99383
138656
145436
147629
93967
51025
65331
60840
107446
111838
141670
50525
65184
69395
97656
134532
58736
128628
72953
70120
106579
143623
54821
71995
96737
62807
51621
103005
108872
45281
132798
102374
108768
140044
141493
138352
137109
45087
132135
135918
61387
49441
111341
64121
118908
54048
144852
87495
62914
81132
135204
148673
55009
54045
63308
123014
83853
106685
100949
143871
132907
67651
132059
126693
119287
131836
53212
102783
89322
48630
116576
90275
118710
148843
44302
104131
84764
141543
136675
122148
120963
110172
76608
60333
100871
125254
120711
148350
132312
130255
59232
119995
45729
56082
65366
135433
95005
109525
132253
110021
91287
118842
89008
113357
130057
51711
95022
100888
143574
110762
52364
118827
82722
67351
131836
124687
96899
127517
130656
94557
59297
59040
53554
89939
141462
124783
63287
73657
102763
84786
91010
59746
99860
98748
92940
139110
85942
69995
79183
138368
148650
122254
125681
114462
57176
137232
58208
43499
111826
75758
143824
41167
69596
101340
115076
78536
73819
113946
73501
68899
123383
144569
126087
83672
131949
52451
106434
74795
125706
76771
124676
91636
53141
113612
71611
111387
90486
116220
86323
67650
99918
121884
75228
102149
68957
81353
66619
109620
114785
53184
134513
109876
87642
144776
93032
43527
143419
80565
76202
84957
82488
75051
119000
90244
110666
115681
59719
128616
80493
102745
57214
41448
148374
137780
126273
87179
108465
57116
110215
118763
67856
116162
70796
118294
65398
103274
107340
71344
97162
92672
54151
117947
149025
107964
115305
43429
105119
54859
76135
110924
54396
80609
43534
99777
58005
82815
109880
94476
101923
113997
57646
62007
45210
133775
122515
120876
58696
134074
65287
65573
120114
126531
52008
93934
107374
92647
127046
123382
94710
97738
50566
61826
96149
83127
139937
42989
121218
65517
84926
44553
70840
149198
145959
41821
84953
76585
116026
45287
138875
81767
67424
53139
125675
122403
125273
74910
70257
94248
97466
65060
84279
110392
54089
74352
81479
76676
104259
56961
90001
57565
128332
149282
128940
100217
96060
97895
79641
47164
108110
78038
75896
97191
55724
111014
81942
68444
142538
93074
84770
136166
81482
106777
84906
122748
127010
60478
141367
63241
137883
91425
120313
72959
104818
85183
135589
137251
63062
111242
63812
106620
50972
74463
64742
93483
126046
85669
122211
80918
103938
58254
103794
69442
78255
113284
144807
105755
102744
123420
66999
88905
103574
117106
82684
55782
40247
101397
137373
145303
70013
92052
55187
147852
104576
72715
90878
122823
56286
128643
92682
80748
64762
93087
56266
136944
119141
125001
59270
60313
116818
133230
107710
93503
141990
107356
40786
104003
44189
80275
144423
108855
118623
129045
50524
80907
57090
47229
136666
70430
147332
101148
76220
109313
127428
52374
45657
51686
52618
119802
83469
75643
50502
121540
117655
99736
84583
141422
135438
89696
69005
41511
127921
124368
40538
109833
73166
78083
118432
41363
101886
54800
42629
60624
67434
94767
97091
109108
51495
54431
62103
68635
86937
148729
43562
98045
124547
88853
49923
124970
102702
119108
86370
52975
56271
87832
74035
43967
40051
80513
120521
47997
138593
93568
46225
44934
136477
57731
129170
77597
141539
66952
131825
89898
77389
139546
147569
81154
93578
144807
85839
144193
86692
84644
104216
68515
40394
57184
73338
119318
40288
91784
41312
86065
67478
59592
75199
115443
135735
148714
47894
128475
62786
89597
46616
76034
132176
96166
52078
109988
105848
55439
54961
131678
127162
45289
65903
81148
93811
113511
88560
52692
141851
127606
63982
139314
130377
105976
68342
111664
130265
68439
117890
63247
111474
97694
64308
143355
136952
61322
81269
146781
118200
65260
72058
66116
120879
48211
42200
119435
95059
46567
102904
100934
57801
42779
100587
55248
108084
55111
106565
96102
98591
49598
149350
91245
106847
127513
94656
110488
77935
49451
84755
45182
96215
60081
49033
66441
120510
106471
116063
138273
142322
147500
66057
139567
43891
116428
132859
89186
48790
108765
100705
52521
149630
125638
71499
47975
112130
44963
96411
103551
129395
109501
75131
104399
44613
57818
88279
54047
71949
143810
87094
60914
126414
127805
94695
48642
88261
142776
42041
95428
123437
67283
74511
51769
127953
69686
88000
85155
121559
97815
51439
117408
44963
140535
49753
127345
138665
136302
102726
80014
59525
48261
102599
112209
74547
127445
84387
136213
99356
109104
111747
137548
95690
66209
41358
62994
138804
99963
104773
123831
53316
102154
50719
61164
143277
116379
88186
49193
148750
143836
116547
94727
117248
104335
143587
127665
71007
63920
78136
58594
93073
68649
67375
88646
119551
103126
95843
43780
86520
72338
125885
149321
89049
85809
71232
124663
121609
82120
82364
61127
138793
102843
101621
112731
42482
91986
126382
149649
113349
149101
85006
40460
81260
125941
140778
112222
117298
83564
96309
48833
116464
120563
98986
114531
89657
114995
79222
132714
131579
47196
107292
68373
119857
128282
101589
82949
77862
46586
106675
110672
63798
59964
108561
95749
44850
94029
142225
55135
107983
133732
95455
58458
62171
149757
82601
59898
76570
73590
58098
144046
148084
83710
129307
134259
96595
84054
62996
130779
129592
104676
114984
111406
141616
106319
142941
42299
65846
55801
87143
77450
137884
65297
90279
124245
50626
117291
130906
145823
60653
99269
94661
67112
114659
90737
47405
85260
61248
64283
113245
139720
149132
56378
128472
90229
126445
86906
48086
118823
54046
73205
109005
73212
93308
50813
52721
104614
91730
103824
129078
130701
144843
75006
60746
115516
65705
40884
71974
50891
141365
121775
59325
81576
111532
53098
110470
111450
41697
76950
119090
49688
117670
105070
98036
56232
102726
146214
138264
75620
148030
143763
92325
141609
48764
141377
102736
138744
91614
140256
93716
77558
143217
62055
55972
101429
62617
51648
44745
75990
135506
98983
133816
43885
120557
104887
52218
45930
48321
112637
89606
47338
96123
119695
142941
103400
47600
115837
46689
117409
78880
86029
127489
93452
116757
135262
104579
73586
56912
69779
98000
142882
44202
107096
58982
119184
64751
89314
50557
67457
51378
88371
112214
103302
59224
87737
79276
114067
53350
43312
103158
67379
97244
126005
84903
87592
133460
82916
111140
141129
55448
87021
71727
144566
143468
50380
143449
54916
70397
107357
54999
128404
46350
65480
52726
148820
134990
52198
69083
69245
148099
50180
46874
138909
94183
104145
49568
102205
86740
117510
88974
100510
141433
110007
48418
95721
147119
100886
75660
85978
66429
92915
141600
103423
58468
80793
51953
73348
126213
147589
146061
45000
42820
119629
76073
77049
124980
114596
114524
139853
71707
122084
79158
46236
137803
40393
116376
71583
59079
109558
62323
140821
100053
119668
120616
46297
119494
84879
60169
108488
111576
138187
67546
78742
126929
88127
70728
82501
79657
78141
140918
91430
61109
101398
88952
42950
58932
92838
55920
106618
69197
126626
88935
94819
83249
65326
96630
73169
69570
103538
115893
76218
61974
117031
81948
54395
55498
104548
142097
114482
116021
70896
113076
113715
69890
140947
149214
113575
51371
76401
93578
88374
80336
80967
146508
81456
80718
99736
117760
78338
59133
89068
72603
50440
97272
138732
138532
110037
72994
141075
91577
120281
88629
100606
76445
40375
75497
86515
75871
40890
104466
80691
51714
90688
122177
122232
117463
103945
56156
76280
67089
52200
61144
42409
97200
73939
54423
72455
87265
62966
117532
43652
99149
68785
144241
80964
146999
78100
143585
103743
100448
130771
103929
52477
59474
82529
73863
51889
82658
65881
136965
146789
89163
76307
115795
50927
71193
135393
90781
40880
123815
80314
77831
76062
105213
111815
146791
92372
124117
144901
106339
91910
105117
88733
70299
51946
105733
42578
95321
75711
108121
57496
128632
94123
122714
42632
145038
92780
105670
99074
66530
147568
65432
120086
66134
119279
72755
117809
107535
85666
137820
58153
45333
100064
52117
133241
113173
115156
131474
99492
134418
101208
115118
147619
48502
72302
51716
91584
55749
52787
129912
79205
64822
59385
100342
75253
146675
51221
102869
142722
103147
128232
93503
71020
54547
42773
70581
59159
134118
137696
115614
133794
77328
72670
63422
68024
69681
149906
123099
57535
46168
69392
67430
90608
59485
52808
129463
80297
123286
48152
68759
77591
94465
73431
114505
86296
138061
50288
107793
112062
73642
62361
42854
94415
141662
147302
106434
86862
143998
97906
114716
78887
101099
57597
102491
116098
112637
71607
129744
105288
136949
56819
137216
45631
110389
90281
139958
47271
54714
57926
93936
63785
112131
110045
57592
105249
84269
63063
91529
104332
143168
118751
96362
104915
111298
99785
120862
149873
110133
105988
84544
68056
122311
89404
101346
54960
80538
43643
142613
101880
90573
55058
49741
115345
41739
133039
88199
144997
126212
72876
69979
92025
52720
92242
146477
115418
72783
60572
148983
121627
113139
78380
64429
141350
61222
115211
67466
61594
116884
141367
115297
128823
64829
102590
83780
65907
51481
104674
92070
87696
115994
104902
76361
147108
121052
101040
113485
42622
121342
76465
53799
112735
59343
145549
64640
141656
140815
140391
97998
132827
79765
69985
95457
56146
46319
42316
77951
51911
62705
117192
74115
149167
114342
81780
85501
94900
45254
149160
132160
119622
100587
40280
79665
88297
119967
94071
99126
106227
114166
48481
83592
84629
49715
123460
121032
67421
104667
90243
78356
138278
105147
114092
54599
129785
61484
133112
82333
118975
122385
123015
118471
55713
90707
85957
99361
141979
89279
57660
118794
40345
53179
84706
100721
109325
131463
123385
48457
70452
142333
148173
67433
117326
84255
133420
87589
54547
115972
73313
72612
124113
84850
63378
81696
45379
60514
108477
81181
106430
125677
57939
44298
83142
95615
120927
99322
92433
148281
111852
84024
78662
75894
73809
145548
84943
136885
133986
52136
69199
85055
120068
52581
120808
72315
75657
139193
131512
146875
116731
70651
49511
96053
124308
136967
123723
122077
90736
124866
90370
148268
71091
143739
105618
118641
94618
139914
123496
125758
145577
50290
62887
146040
129231
145642
84563
96549
40973
91290
139770
65198
111061
88805
121407
112181
148785
80506
131116
137298
75250
76712
131526
137117
50119
133147
68824
128379
93957
81141
46560
87960
128212
120669
59750
121559
70078
116333
45955
119176
73360
138199
116238
107081
98612
138961
67633
79661
62306
54207
65304
134866
55871
116797
126135
106808
117817
102651
66351
53782
113982
125382
149117
94656
148991
124753
142474
144422
78993
43800
121483
59787
88190
121711
123741
121196
91099
60269
49611
74308
59182
66353
86197
137780
49583
100348
65393
91373
132372
61058
120867
140068
91816
71665
134646
99267
54671
80530
98856
112772
40741
58570
96940
69172
146008
112262
137761
57206
112714
58909
92762
129341
146272
105240
103650
132540
127353
67297
128035
94227
114426
125990
122188
70100
79170
114347
105086
55252
52822
58329
141339
121229
149809
135714
89874
125549
42147
100282
100356
49903
66181
128116
112302
65478
145564
86128
144095
50817
87506
85490
123564
143310
125575
116703
108731
92736
100854
87612
72005
76620
132696
103049
78318
41437
138568
80639
43146
57369
82366
92647
97281
96969
78393
105451
132062
87804
42112
128751
52163
100645
121444
83194
146869
112966
99265
67431
62940
130489
85881
120372
124342
130859
87960
79515
78975
141209
145416
72751
97411
55810
132178
43119
112902
124550
50033
98302
112631
56208
69465
69139
106087
112128
89931
89746
87172
144965
121838
46964
83336
87112
144105
56962
131586
59832
76217
106680
125520
55275
121354
71399
114124
88551
52972
67946
76958
75535
91886
98159
78849
82975
92336
141002
55609
117354
99502
85930
60559
68040
139682
52630
65549
147450
92497
145454
71848
51322
113972
140032
109064
126752
94233
104496
132150
99096
53216
132936
46861
47138
105384
68513
67416
41642
144939
45517
79907
102071
143896
103996
92790
145180
55248
91510
144479
122795
59886
41881
55277
113841
56975
56039
63283
143871
129835
132527
91267
106504
95695
83026
129260
54078
124247
140610
131998
57188
142495
71982
80832
127262
130421
118424
84976
62074
70684
139605
146143
132813
144128
91228
75119
113311
85403
94777
45945
52740
85417
72547
143109
145746
101497
135206
143728
98515
94139
61127
46202
67703
143419
63342
51065
106915
79037
124809
107769
139092
130382
69817
54522
117406
102877
97743
46823
46747
43934
67947
119624
48040
84351
129427
116829
88014
69130
75153
76097
135748
133119
128759
107226
51735
107237
128382
133128
145528
87592
53012
58025
72980
47476
98980
126718
100960
67849
106615
90027
59155
102492
111986
43256
40275
106766
94141
51362
82348
51615
94856
40680
88158
71636
68271
131019
85980
93409
97669
101289
77327
129504
45165
145859
146280
124792
95843
133092
126617
90471
46300
143549
69192
47959
61765
74824
42888
71169
115421
130358
125209
120857
73126
44406
55963
61294
44904
75474
109522
57820
79184
125577
52852
56975
69240
99330
92264
75850
118435
73042
110402
59158
69773
102354
58752
80599
148327
65070
89814
77715
81649
45254
97231
69744
62939
41971
125298
134661
101355
90283
47358
141022
115884
134011
130006
88550
103812
82515
52235
56411
127208
43264
138155
129396
135894
76963
81757
140241
114561
91123
93896
108948
97600
93932
58299
113754
104184
48223
44349
110588
79667
146160
131368
61205
73925
92355
44262
136381
109065
77110
82579
136928
77852
109970
108418
110751
91156
53957
48823
82700
135934
82645
136709
41630
141209
146497
86500
92190
77414
120199
125353
143771
130377
116302
89804
100033
111185
136184
145942
146526
147928
80325
87191
71666
137361
106114
103258
73673
56335
135422
77913
129565
123563
117971
87488
130624
86106
70940
54944
84156
54699
108559
103180
93430
137581
58924
71911
114678
71389
105512
96293
87671
40250
96774
141011
71989
138476
71324
147284
149841
61776
71109
103748
140765
69472
126477
116467
71164
70880
110273
122174
102836
126013
146895
148149
46379
102253
147552
58405
129445
72330
126703
56259
44463
120846
96566
45782
119907
119984
112327
61931
103482
134278
119162
74224
95777
49885
80716
64056
73542
67133
121649
97571
40548
58556
125894
123457
94545
68781
128961
55628
49393
74803
41288
120577
62379
65979
45519
82949
124155
112380
120324
50829
122525
59706
71859
80157
129196
144354
136838
142709
119344
109955
127149
72463
108827
116919
110988
120082
63631
142466
46899
85811
113339
48930
75621
105643
61800
42936
78005
61560
72199
77482
109881
134551
137371
84194
148429
50658
117556
129302
65225
45850
55707
133544
75562
40345
119194
62834
142051
115331
149231
59664
40652
126816
74584
110895
88870
87212
142565
123283
91440
48969
118623
91947
101637
73862
84990
139320
81246
91984
53613
141733
147005
77676
48371
123641
120614
114133
143609
108838
115891
72014
80848
137538
60286
93240
77838
97609
41781
65191
140861
136536
78543
61729
50414
99836
93449
131370
69332
137289
120248
149256
62195
121818
98461
78887
133798
40947
65272
93995
109163
89015
44982
81832
105696
52097
114710
59248
104796
106866
101078
107807
70106
87360
134791
100966
70299
138346
129039
143131
143391
55706
79748
43549
95233
64643
130432
75409
114800
58493
112251
82477
110566
146414
41071
56668
47179
133284
134362
72015
94550
68141
106489
139873
68650
68424
106957
148200
87019
47776
118512
46947
59656
77012
128516
45295
40411
86723
48241
114792
110460
65212
49963
40324
138236
77641
83109
142878
61337
58893
144657
104800
118170
49193
100465
70357
127183
143114
123662
94544
41924
142847
144433
76840
148727
124759
106924
76041
139949
140281
122690
44181
67240
78001
85758
62445
53382
74697
60233
46350
118143
49577
133490
58748
70833
80907
141213
52742
52645
53901
58214
78601
61133
66627
88318
65886
129764
56807
102861
47036
103794
56447
124592
111074
51138
82735
95461
114011
111847
129068
81200
126953
74428
100045
133876
134958
57469
99219
73660
142708
45253
82747
135016
88561
74146
121456
63604
104828
72533
72617
114667
134910
68626
94516
42358
97532
136415
125308
123240
109735
145998
139690
102342
102119
60387
45168
125135
141854
139799
116088
42969
84076
55575
88112
56429
129921
103357
99155
137622
53983
59103
93526
120274
86187
94430
102463
109741
88023
52111
109275
120377
126847
48134
93266
71683
63356
54456
115402
145578
100030
53662
61609
46530
136226
147479
76641
79952
139141
94471
56027
94599
133207
66627
128538
89958
108742
50482
62871
103003
95677
98968
60122
112778
62367
114919
144381
57720
79945
79382
147083
122650
63643
67568
131463
48558
107685
71853
142272
148844
133253
56112
62252
125668
99431
83592
41890
130362
81251
144438
146277
73172
109807
103449
66906
141293
129122
55744
138280
98507
103780
49287
51145
112380
95912
92874
51470
105215
91949
66184
126062
71818
63537
85461
105480
42499
144761
120358
129780
62673
137364
131167
70675
113704
130260
49506
109442
132109

Way faster

**Professional Rule:** Never use iterrows() unless absolutely necessary.

**7. query()**\
Normal filtering:

In [25]:
df[
    (df["Salary"] > 80000)
    &
    (df["Department"]=="IT")
]

          ID Department  Salary    Bonus
5          5         IT  148262  14826.2
6          6         IT  138500  13850.0
11        11         IT  123922  12392.2
16        16         IT   99670   9967.0
19        19         IT  140904  14090.4
...      ...        ...     ...      ...
99988  99988         IT  134227  13422.7
99989  99989         IT  142039  14203.9
99992  99992         IT  107625  10762.5
99994  99994         IT  114207  11420.7
99998  99998         IT  139619  13961.9

[21286 rows x 4 columns]

Alternative:

In [26]:
df.query(
    "Salary > 80000 and Department=='IT'"
)

          ID Department  Salary    Bonus
5          5         IT  148262  14826.2
6          6         IT  138500  13850.0
11        11         IT  123922  12392.2
16        16         IT   99670   9967.0
19        19         IT  140904  14090.4
...      ...        ...     ...      ...
99988  99988         IT  134227  13422.7
99989  99989         IT  142039  14203.9
99992  99992         IT  107625  10762.5
99994  99994         IT  114207  11420.7
99998  99998         IT  139619  13961.9

[21286 rows x 4 columns]

**Advantages:**\
Cleaner\
More readable\
Sometimes faster

Industry teams often use:\
query()\
for complex conditions.

**8. eval()**\
Suppose:

In [27]:
df["Tax"] = (
    df["Salary"]*0.2
    +
    df["Bonus"]*0.1
)

Alternative:

In [28]:
df.eval(
    "Tax = Salary*0.2 + Bonus*0.1",
    inplace=True
)

**Benefits:**\
Less temporary memory\
Potentially faster\
Cleaner expressions\
Useful on huge datasets.

**9. Chunk Processing**\
Suppose:\
5 GB CSV\
RAM:\
8 GB\
You cannot load everything.

Instead of Entire file, you load in chunks and keep processing

This is how ETL pipelines work.

**10. Efficient CSV Reading**\
Read Specific Columns\
Bad:\
pd.read_csv(\
    "data.csv"\
)\
Better:\
pd.read_csv(\
    "data.csv",\
    usecols=["Salary","Department"]\
)\
**Specify Data Types**\
Bad:\
pd.read_csv(\
    "data.csv"\
)\
Better:\
pd.read_csv(\
    "data.csv",\
    dtype={\
        "Salary":"int32",\
        "Department":\
        "category"\
    }\
)\
This saves memory immediately.

**11. Copy vs View**\
This causes --> SettingWithCopyWarning

Bad:

In [29]:
high_salary = df[
    df["Salary"] > 80000
]

high_salary["Bonus"] = 10000

C:\Users\talpu\AppData\Local\Temp\ipykernel_23192\2111818719.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_salary["Bonus"] = 10000

Correct way:

In [31]:
high_salary = df[
    df["Salary"] > 80000
].copy()

Now, following line works safely:

In [32]:
high_salary["Bonus"] = 10000

**Professional Rule**: If you're creating a separate DataFrame, .copy() is your friend.

**12. apply() vs Vectorization**\
Bad:

In [33]:
df["Bonus"] = df[
    "Salary"
].apply(

    lambda x:
    x*0.1
)

Better:

In [34]:
df["Bonus"] = (
    df["Salary"]
    * 0.1
)

Vectorization almost always wins