# <center> Data Cleaning Mastery
Before analysis, visualization, or machine learning, data must be cleaned.

**The Data Cleaning Workflow**

Whenever you load a dataset:

1. Inspect
2. Find Missing Values
3. Handle Missing Values
4. Find Duplicates
5. Remove Duplicates
6. Check Data Types
7. Fix Data Types
8. Clean Text Columns
9. Verify Results

This workflow should become automatic.

Let's create our dataset to work on

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Ali","Sara","Ahmed","Ahmed","  Bilal","AYESHA"],
    "Age":[22,np.nan,30,30,35,28],
    "Salary":[50000,70000,np.nan,np.nan,120000,80000],
    "Department":["HR","IT","IT","IT","HR","Finance"]
})
print(df)

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara   NaN   70000.0         IT
2    Ahmed  30.0       NaN         IT
3    Ahmed  30.0       NaN         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**1. Detect Missing Values**

In [50]:
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False    True       False
4  False  False   False       False
5  False  False   False       False

True --> missing\
False --> present

**Count Missing Values**

In [51]:
df.isna().sum()

Name          0
Age           1
Salary        2
Department    0
dtype: int64

**Interpretation:**\
Age has 1 missing value\
Salary has 2 missing values

**2. Handling Missing Values**\
There is no universal solution.\
It depends on context.

**Method 1:** Drop rows\
Remove rows containing missing values.\
Only complete rows remain.\
Note: Should be used only when only a few rows are missing relative to the total.

In [52]:
df.dropna()

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

Not beneficial in this case because, out of 5 rows, 2 contain missing values, removing which removes almost half the dataset.

**Method 2:** Fill with constant

In [53]:
df.fillna("Unknown")

      Name      Age    Salary Department
0      Ali     22.0   50000.0         HR
1     Sara  Unknown   70000.0         IT
2    Ahmed     30.0   Unknown         IT
3    Ahmed     30.0   Unknown         IT
4    Bilal     35.0  120000.0         HR
5   AYESHA     28.0   80000.0    Finance

Useful for categorical columns

**Method 3:** Fill with mean\
Very common.

In [3]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara  29.0   70000.0         IT
2    Ahmed  30.0       NaN         IT
3    Ahmed  30.0       NaN         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**Method 4:** Fill with Median\
preferred when outliers exist

In [4]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara  29.0   70000.0         IT
2    Ahmed  30.0   75000.0         IT
3    Ahmed  30.0   75000.0         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**Method 5:** Fill with Mode\
Most frequent value

In [56]:
df["Department"].mode()

0    IT
Name: Department, dtype: object

In [57]:
df["Department"].fillna(df["Department"].mode())

0         HR
1         IT
2         IT
3         IT
4         HR
5    Finance
Name: Department, dtype: object

Useful for categorical columns

**3. Forward Fill:**\
Common in time series

In [11]:
df.ffill()

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara  22.0   70000.0         IT
2    Ahmed  30.0   70000.0         IT
3    Ahmed  30.0   70000.0         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**4. Backward Fill**

In [13]:
df.bfill()

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara  30.0   70000.0         IT
2    Ahmed  30.0  120000.0         IT
3    Ahmed  30.0  120000.0         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**5. Detect Duplicates**

In [14]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

**Count Duplicates**

In [16]:
df.duplicated().sum()

np.int64(1)

**Remove Duplicates**

In [5]:
df = df.drop_duplicates()

In [59]:
df

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     Sara  29.0   70000.0         IT
2    Ahmed  30.0   75000.0         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

**6. DataType Inspection**

In [60]:
df.dtypes

Name           object
Age           float64
Salary        float64
Department     object
dtype: object

**7. Converting Data Types**

astype(): Convert to specific datatype

In [6]:
df["Age"]=df["Age"].astype(int)

C:\Users\talpu\AppData\Local\Temp\ipykernel_21292\2332842721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].astype(int)

In [62]:
df.dtypes

Name           object
Age             int64
Salary        float64
Department     object
dtype: object

**Common Real-World Problem**\
CSV:\
Age\
22\
25\
30\
Unknown\
Column becomes:\
object\
instead of:\
int

In [14]:
age = pd.Series([22,25,30,"unknown"])
print(f"Datatype due to unknown: {age.dtype}")
age = pd.to_numeric(age,errors="coerce")
print(f"Datatype after handling with pd.to_numeric():\n{age}")

Datatype due to unknown: object
Datatype after handling with pd.to_numeric():
0    22.0
1    25.0
2    30.0
3     NaN
dtype: float64

Unknowns become NaN which can then be handled.

**8. Renaming Columns**

In [19]:
df2 = pd.DataFrame({
    "cust_age":[12,16],
    "cust_sal":[20000,23000]
})
print(f"Before renaming: \n{df2}")
df2 = df2.rename(
    columns={
        "cust_age":"Age",
        "cust_sal":"Salary"
    }
)
print(f"After renaming: \n{df2}")

Before renaming:
   cust_age  cust_sal
0        12     20000
1        16     23000
After renaming:
   Age  Salary
0   12   20000
1   16   23000

**9. Text Cleaning**

a) strip()\
remove extra whitespaces

In [25]:
df["Name"] = df["Name"].str.strip()
df

C:\Users\talpu\AppData\Local\Temp\ipykernel_21292\1011139634.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Name"] = df["Name"].str.strip()

     Name  Age    Salary Department
0     ali   22   50000.0         HR
1    sara   29   70000.0         IT
2   ahmed   30   75000.0         IT
4   bilal   35  120000.0         HR
5  ayesha   28   80000.0    Finance

b) lower()\
converts to lower-case

In [24]:
df.loc[:,"Name"] = df.loc[:,"Name"].str.lower()
df

     Name  Age    Salary Department
0     ali   22   50000.0         HR
1    sara   29   70000.0         IT
2   ahmed   30   75000.0         IT
4   bilal   35  120000.0         HR
5  ayesha   28   80000.0    Finance

c) upper()\
converts to upper-case

In [27]:
df.loc[:,"Name"] = df["Name"].str.upper()
df

     Name  Age    Salary Department
0     ALI   22   50000.0         HR
1    SARA   29   70000.0         IT
2   AHMED   30   75000.0         IT
4   BILAL   35  120000.0         HR
5  AYESHA   28   80000.0    Finance

d) title()\
converts to title case\
industry favorite

In [29]:
df.loc[:,"Name"] = df["Name"].str.title()
df

     Name  Age    Salary Department
0     Ali   22   50000.0         HR
1    Sara   29   70000.0         IT
2   Ahmed   30   75000.0         IT
4   Bilal   35  120000.0         HR
5  Ayesha   28   80000.0    Finance

e) replace\
replaces specific values in specific columns with other values

In [32]:
df.loc[:,"Department"] = df["Department"].replace({
    "HR":"Human Resources",
    "IT":"Information Technology"
})
df

     Name  Age    Salary              Department
0     Ali   22   50000.0         Human Resources
1    Sara   29   70000.0  Information Technology
2   Ahmed   30   75000.0  Information Technology
4   Bilal   35  120000.0         Human Resources
5  Ayesha   28   80000.0                 Finance

**10. Verification**

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Salary      5 non-null      float64
 3   Department  5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 200.0+ bytes

In [34]:
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2  False  False   False       False
4  False  False   False       False
5  False  False   False       False

In [35]:
df.isna().sum()

Name          0
Age           0
Salary        0
Department    0
dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.dtypes

Name           object
Age             int64
Salary        float64
Department     object
dtype: object

In [39]:
df.head()

     Name  Age    Salary              Department
0     Ali   22   50000.0         Human Resources
1    Sara   29   70000.0  Information Technology
2   Ahmed   30   75000.0  Information Technology
4   Bilal   35  120000.0         Human Resources
5  Ayesha   28   80000.0                 Finance

**Industry Data Cleaning Checklist**\
Whenever you load data:\
df.head()\
df.info()\
df.isna().sum()\
df.duplicated().sum()\
df.dtypes\
These 5 checks should become muscle memory.

### <center> Practice Problems

**Problem 1**
  
Create a DataFrame with missing ages.

Find:

df.isna()\
df.isna().sum()

In [53]:
df = pd.DataFrame({
    "Name":[" Ali"," SARA","ahmed","ahmed","  Bilal","AYESHA"],
    "Age":[22,np.nan,30,30,35,28],
    "Salary":[50000,70000,np.nan,np.nan,120000,80000],
    "Department":["HR","IT","IT","IT","HR","Finance"]
})
print(df)

      Name   Age    Salary Department
0      Ali  22.0   50000.0         HR
1     SARA   NaN   70000.0         IT
2    ahmed  30.0       NaN         IT
3    ahmed  30.0       NaN         IT
4    Bilal  35.0  120000.0         HR
5   AYESHA  28.0   80000.0    Finance

In [54]:
df["Age"].isna()

0    False
1     True
2    False
3    False
4    False
5    False
Name: Age, dtype: bool

In [55]:
df["Age"].isna().sum()

np.int64(1)

**Problem 2**

Fill missing ages with:

mean

In [56]:
df.loc[:,"Age"] = df["Age"].mean()
df

      Name   Age    Salary Department
0      Ali  29.0   50000.0         HR
1     SARA  29.0   70000.0         IT
2    ahmed  29.0       NaN         IT
3    ahmed  29.0       NaN         IT
4    Bilal  29.0  120000.0         HR
5   AYESHA  29.0   80000.0    Finance

**Problem 3**

Fill missing salaries with:

median

In [57]:
df.loc[:,"Salary"] = df["Salary"].median()
df

      Name   Age   Salary Department
0      Ali  29.0  75000.0         HR
1     SARA  29.0  75000.0         IT
2    ahmed  29.0  75000.0         IT
3    ahmed  29.0  75000.0         IT
4    Bilal  29.0  75000.0         HR
5   AYESHA  29.0  75000.0    Finance

**Problem 4**

Create duplicate employee rows.

Detect duplicates.

In [58]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [59]:
df.duplicated().sum()

np.int64(1)

In [60]:
df[df.duplicated()].index

Index([3], dtype='int64')

**Problem 5**

Remove duplicates.

Verify removal.

In [61]:
df = df.drop_duplicates()
df

      Name   Age   Salary Department
0      Ali  29.0  75000.0         HR
1     SARA  29.0  75000.0         IT
2    ahmed  29.0  75000.0         IT
4    Bilal  29.0  75000.0         HR
5   AYESHA  29.0  75000.0    Finance

In [62]:
df.duplicated().sum()

np.int64(0)

**Problem 6**

Create names with:

"  Ali"\
" SARA "\
"ahmed"

Clean them using:

str.strip()\
str.title()

In [64]:
df.loc[:,"Name"] = df["Name"].str.strip()
df.loc[:,"Name"] = df["Name"].str.title()
df

     Name   Age   Salary Department
0     Ali  29.0  75000.0         HR
1    Sara  29.0  75000.0         IT
2   Ahmed  29.0  75000.0         IT
4   Bilal  29.0  75000.0         HR
5  Ayesha  29.0  75000.0    Finance

**Problem 7**

Create:

Age\
22\
25\
Unknown\
30

Convert to numeric.

Handle invalid values.

In [67]:
ages = pd.Series([22,25,"Unknown",30])
ages = pd.to_numeric(ages,errors="coerce")
ages

0    22.0
1    25.0
2     NaN
3    30.0
dtype: float64

**Problem 8**

Rename:

cust_age\
cust_salary

to:

Age
Salary

In [71]:
p8 = pd.DataFrame({
    "cust_age" : [12,13,16],
    "cust_sal" : [2000,3000,4000]
})
print(f"Before:\n{p8}")
p8 = p8.rename(
    columns = {
        "cust_age" : "Age",
        "cust_sal" : "Salary"
}
)
print(f"After\n{p8}")

Before:
   cust_age  cust_sal
0        12      2000
1        13      3000
2        16      4000
After
   Age  Salary
0   12    2000
1   13    3000
2   16    4000