# <center>Window Functions and Analytical Operations

Window Functions answer "Tell me something about each row using information from surrounding rows"\
This is exactly how analysts, financial engineers and data scientists analyze trends.\
**What are window functions?**\
Imagine daily sales:\
Day 1 --> 100\
Day 2 --> 120\
Day 3 --> 150\
Day 4 --> 90\
Day 5 --> 180\
Instead of asking: "Total sales?"\
Ask : \
"Average of last 3 days?"\
"Difference from yesterday?"\
"Growth since yesterday?"\
"Running total?"\
"Rank among employees?"\
"Highest sale so far?"\
These are all window operations

**Dataset**

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Date":pd.date_range(
        "2025-01-01",
        periods=10
    ),
    "Sales":[100,120,150,130,160,180,170,210,220,200],
    "Employee":["A","A","A","A","A","B","B","B","B","B"]
})

df

        Date  Sales Employee
0 2025-01-01    100        A
1 2025-01-02    120        A
2 2025-01-03    150        A
3 2025-01-04    130        A
4 2025-01-05    160        A
5 2025-01-06    180        B
6 2025-01-07    170        B
7 2025-01-08    210        B
8 2025-01-09    220        B
9 2025-01-10    200        B

**1. shift()**\
Probably the most used window function\
It moves values without changing the index\
Current row can "look" at previous or next rows

In [2]:
df["Sales"].shift(1)

0      NaN
1    100.0
2    120.0
3    150.0
4    130.0
5    160.0
6    180.0
7    170.0
8    210.0
9    220.0
Name: Sales, dtype: float64

Previous Day Sales:

In [3]:
df["Yesterday"] = df["Sales"].shift(1)
df

        Date  Sales Employee  Yesterday
0 2025-01-01    100        A        NaN
1 2025-01-02    120        A      100.0
2 2025-01-03    150        A      120.0
3 2025-01-04    130        A      150.0
4 2025-01-05    160        A      130.0
5 2025-01-06    180        B      160.0
6 2025-01-07    170        B      180.0
7 2025-01-08    210        B      170.0
8 2025-01-09    220        B      210.0
9 2025-01-10    200        B      220.0

Next day sales:

In [4]:
df["Tomorrow"] = df["Sales"].shift(-1)
df

        Date  Sales Employee  Yesterday  Tomorrow
0 2025-01-01    100        A        NaN     120.0
1 2025-01-02    120        A      100.0     150.0
2 2025-01-03    150        A      120.0     130.0
3 2025-01-04    130        A      150.0     160.0
4 2025-01-05    160        A      130.0     180.0
5 2025-01-06    180        B      160.0     170.0
6 2025-01-07    170        B      180.0     210.0
7 2025-01-08    210        B      170.0     220.0
8 2025-01-09    220        B      210.0     200.0
9 2025-01-10    200        B      220.0       NaN

**2. diff()**\
Difference between consecutive rows\
Formula : Current - Previous

In [5]:
df["Daily Change"] = df["Sales"].diff()
df

        Date  Sales Employee  Yesterday  Tomorrow  Daily Change
0 2025-01-01    100        A        NaN     120.0           NaN
1 2025-01-02    120        A      100.0     150.0          20.0
2 2025-01-03    150        A      120.0     130.0          30.0
3 2025-01-04    130        A      150.0     160.0         -20.0
4 2025-01-05    160        A      130.0     180.0          30.0
5 2025-01-06    180        B      160.0     170.0          20.0
6 2025-01-07    170        B      180.0     210.0         -10.0
7 2025-01-08    210        B      170.0     220.0          40.0
8 2025-01-09    220        B      210.0     200.0          10.0
9 2025-01-10    200        B      220.0       NaN         -20.0

**3. pct_change()**\
Percentage growth\
Formula: (Current - Pevious) / Previous

In [6]:
df["Growth"] = df["Sales"].pct_change()
df

        Date  Sales Employee  Yesterday  Tomorrow  Daily Change    Growth
0 2025-01-01    100        A        NaN     120.0           NaN       NaN
1 2025-01-02    120        A      100.0     150.0          20.0  0.200000
2 2025-01-03    150        A      120.0     130.0          30.0  0.250000
3 2025-01-04    130        A      150.0     160.0         -20.0 -0.133333
4 2025-01-05    160        A      130.0     180.0          30.0  0.230769
5 2025-01-06    180        B      160.0     170.0          20.0  0.125000
6 2025-01-07    170        B      180.0     210.0         -10.0 -0.055556
7 2025-01-08    210        B      170.0     220.0          40.0  0.235294
8 2025-01-09    220        B      210.0     200.0          10.0  0.047619
9 2025-01-10    200        B      220.0       NaN         -20.0 -0.090909

Multiply by 100 if desired

In [9]:
df["Growth %"] = (
    df["Sales"]
    .pct_change()
    *100
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909

**4. cumsum()**\
Running Total

In [10]:
df["Running Sales"] = df["Sales"].cumsum()
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640

**5. cummax()**\
Maximum value so far

In [11]:
df["Highest"] = df["Sales"].cummax()

In [12]:
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220

**6. cummin()**\
Lowest value encountered

In [13]:
df["Lowest"] = df["Sales"].cummin()
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100

**7. cumprod()**\
Running Multiplication

In [14]:
s = pd.Series([2,3,4])
s.cumprod()

0     2
1     6
2    24
dtype: int64

**8. rank()**\
Rank rows

In [16]:
df["Rank"] = df["Sales"].rank(ascending=False)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0

Methods:

In [17]:
df["Rank_Avg"] = df["Sales"].rank(method="average")
df["Rank_Dense"] = df["Sales"].rank(method="dense")
df["Rank_first"] = df["Sales"].rank(method="first")
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0

**9. rolling()**\
The king of window functions

Three Day Moving Average

In [19]:
df["Rolling Mean"] = (
    df["Sales"]
    .rolling(window=3)
    .mean()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0,NaN
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0,123.333333
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0,133.333333
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0,146.666667
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0,156.666667
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0,170.000000
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0,186.666667
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0,200.000000
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0,210.000000

Rolling sum

In [20]:
df["Rolling Sum"] = (
    df["Sales"]
    .rolling(window=3)
    .sum()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0,NaN,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0,NaN,NaN
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0,123.333333,370.0
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0,133.333333,400.0
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0,146.666667,440.0
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0,156.666667,470.0
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0,170.000000,510.0
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0,186.666667,560.0
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0,200.000000,600.0
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0,210.000000,630.0

Rolling min

In [21]:
df["Rolling Minimum"] = (
    df["Sales"]
    .rolling(window=3)
    .min()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0,NaN,NaN,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0,NaN,NaN,NaN
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0,123.333333,370.0,100.0
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0,133.333333,400.0,120.0
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0,146.666667,440.0,130.0
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0,156.666667,470.0,130.0
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0,170.000000,510.0,160.0
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0,186.666667,560.0,170.0
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0,200.000000,600.0,170.0
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0,210.000000,630.0,200.0

Rolling Max

In [22]:
df["Rolling Max"] = (
    df["Sales"]
    .rolling(window=3)
    .max()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum,Rolling Max
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0,123.333333,370.0,100.0,150.0
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0,133.333333,400.0,120.0,150.0
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0,146.666667,440.0,130.0,160.0
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0,156.666667,470.0,130.0,180.0
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0,170.000000,510.0,160.0,180.0
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0,186.666667,560.0,170.0,210.0
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0,200.000000,600.0,170.0,220.0
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0,210.000000,630.0,200.0,220.0

Rolling Standard Deviation

In [23]:
df["Rolling Std"] = (
    df["Sales"]
    .rolling(window=3)
    .std()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,Lowest,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum,Rolling Max,Rolling Std
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,100,10.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,100,9.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,100,7.0,4.0,4.0,4.0,123.333333,370.0,100.0,150.0,25.166115
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,100,8.0,3.0,3.0,3.0,133.333333,400.0,120.0,150.0,15.275252
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,100,6.0,5.0,5.0,5.0,146.666667,440.0,130.0,160.0,15.275252
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,100,4.0,7.0,7.0,7.0,156.666667,470.0,130.0,180.0,25.166115
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,100,5.0,6.0,6.0,6.0,170.000000,510.0,160.0,180.0,10.000000
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,100,2.0,9.0,9.0,9.0,186.666667,560.0,170.0,210.0,20.816660
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,100,1.0,10.0,10.0,10.0,200.000000,600.0,170.0,220.0,26.457513
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,100,3.0,8.0,8.0,8.0,210.000000,630.0,200.0,220.0,10.000000

**10. expanding()**\
Unlike rolling, it never forgets previous rows\
Happens to behave like cumulative functions

In [24]:
df["Expanding Mean"] = (
    df["Sales"]
    .expanding()
    .mean()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,...,Rank,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum,Rolling Max,Rolling Std,Expanding Mean
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,...,10.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,100.000000
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,...,9.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,110.000000
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,...,7.0,4.0,4.0,4.0,123.333333,370.0,100.0,150.0,25.166115,123.333333
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,...,8.0,3.0,3.0,3.0,133.333333,400.0,120.0,150.0,15.275252,125.000000
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,...,6.0,5.0,5.0,5.0,146.666667,440.0,130.0,160.0,15.275252,132.000000
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,...,4.0,7.0,7.0,7.0,156.666667,470.0,130.0,180.0,25.166115,140.000000
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,...,5.0,6.0,6.0,6.0,170.000000,510.0,160.0,180.0,10.000000,144.285714
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,...,2.0,9.0,9.0,9.0,186.666667,560.0,170.0,210.0,20.816660,152.500000
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,...,1.0,10.0,10.0,10.0,200.000000,600.0,170.0,220.0,26.457513,160.000000
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,...,3.0,8.0,8.0,8.0,210.000000,630.0,200.0,220.0,10.000000,164.000000

**11. ewm()**\
Exponentially Weighted Moving Average

In [25]:
df["EWMA"] = (
    df["Sales"]
    .ewm(alpha=0.3)
    .mean()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,...,Rank_Avg,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum,Rolling Max,Rolling Std,Expanding Mean,EWMA
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,100.000000,100.000000
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,...,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,110.000000,111.764706
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,...,4.0,4.0,4.0,123.333333,370.0,100.0,150.0,25.166115,123.333333,129.223744
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,...,3.0,3.0,3.0,133.333333,400.0,120.0,150.0,15.275252,125.000000,129.530201
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,...,5.0,5.0,5.0,146.666667,440.0,130.0,160.0,15.275252,132.000000,140.517832
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,...,7.0,7.0,7.0,156.666667,470.0,130.0,180.0,25.166115,140.000000,153.941799
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,...,6.0,6.0,6.0,170.000000,510.0,160.0,180.0,10.000000,144.285714,159.191603
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,...,9.0,9.0,9.0,186.666667,560.0,170.0,210.0,20.816660,152.500000,175.366577
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,...,10.0,10.0,10.0,200.000000,600.0,170.0,220.0,26.457513,160.000000,189.319661
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,...,8.0,8.0,8.0,210.000000,630.0,200.0,220.0,10.000000,164.000000,192.616902

**12. Group Wise Window Functions**\
Instead of one running total, Compute per employee

In [26]:
df["Employee Running Sales"] = (
    df
    .groupby("Employee")["Sales"]
    .cumsum()
)
df

,Date,Sales,Employee,Yesterday,Tomorrow,Daily Change,Growth,Growth %,Running Sales,Highest,...,Rank_Dense,Rank_first,Rolling Mean,Rolling Sum,Rolling Minimum,Rolling Max,Rolling Std,Expanding Mean,EWMA,Employee Running Sales
0,2025-01-01,100,A,NaN,120.0,NaN,NaN,NaN,100,100,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,100.000000,100.000000,100
1,2025-01-02,120,A,100.0,150.0,20.0,0.200000,20.000000,220,120,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,110.000000,111.764706,220
2,2025-01-03,150,A,120.0,130.0,30.0,0.250000,25.000000,370,150,...,4.0,4.0,123.333333,370.0,100.0,150.0,25.166115,123.333333,129.223744,370
3,2025-01-04,130,A,150.0,160.0,-20.0,-0.133333,-13.333333,500,150,...,3.0,3.0,133.333333,400.0,120.0,150.0,15.275252,125.000000,129.530201,500
4,2025-01-05,160,A,130.0,180.0,30.0,0.230769,23.076923,660,160,...,5.0,5.0,146.666667,440.0,130.0,160.0,15.275252,132.000000,140.517832,660
5,2025-01-06,180,B,160.0,170.0,20.0,0.125000,12.500000,840,180,...,7.0,7.0,156.666667,470.0,130.0,180.0,25.166115,140.000000,153.941799,180
6,2025-01-07,170,B,180.0,210.0,-10.0,-0.055556,-5.555556,1010,180,...,6.0,6.0,170.000000,510.0,160.0,180.0,10.000000,144.285714,159.191603,350
7,2025-01-08,210,B,170.0,220.0,40.0,0.235294,23.529412,1220,210,...,9.0,9.0,186.666667,560.0,170.0,210.0,20.816660,152.500000,175.366577,560
8,2025-01-09,220,B,210.0,200.0,10.0,0.047619,4.761905,1440,220,...,10.0,10.0,200.000000,600.0,170.0,220.0,26.457513,160.000000,189.319661,780
9,2025-01-10,200,B,220.0,NaN,-20.0,-0.090909,-9.090909,1640,220,...,8.0,8.0,210.000000,630.0,200.0,220.0,10.000000,164.000000,192.616902,980